openapi: 3.0.3
info:
  title: OIF Solver Authentication API
  description: |
    API endpoints for JWT-based authentication and authorization for the OIF Solver.

    ## Authentication Flow

    1. **Privileged Client Auth**: POST /auth/token with `client_id + client_secret` to obtain admin access token
    2. **Optional Public Registration**: POST /auth/register (if enabled) for non-admin scopes
    3. **API Access**: Include access token in Authorization header: `Bearer <access_token>`
    4. **Token Refresh**: For register-issued tokens, POST /auth/refresh with refresh token
    5. **Scope-Based Authorization**: Different endpoints require different scopes

    ## Token Lifecycle

    - **Access Tokens**: Short-lived, used for API authentication
    - **Client Credentials Tokens**: Default 900 seconds, no refresh token
    - **Refresh Tokens**: Long-lived (default 30 days), used to obtain new access tokens
    - **Token Rotation**: Refresh endpoint returns a new refresh token

    ## Scopes

    - `read-orders`: Read access to order information (GET /orders/{id})
    - `create-orders`: Permission to create new orders (POST /orders)
    - `admin-all`: Full administrative access to all endpoints

    ## Security Notes

    - Authentication is optional and configured per solver instance
    - If `auth.enabled = false`, auth endpoints are unavailable
    - `/auth/register` cannot issue `admin-all`
    - Client IDs must be between 3-100 characters
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.solver.example.com/api/v1
    description: Production server (replace with actual URL)

paths:
  /auth/token:
    post:
      summary: Issue access token with client credentials
      description: |
        Issues an access token for privileged clients using `client_id + client_secret`.
        This endpoint supports `grant_type=client_credentials` and only allows `admin-all`.

        This flow returns an access token only (no refresh token). Clients should request
        a new token when it expires.
      operationId: issueClientToken
      tags:
        - Authentication
      requestBody:
        required: true
        description: Client credentials token request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRequest"
            example:
              grant_type: "client_credentials"
              client_id: "solver-admin"
              client_secret: "replace-with-your-client-secret"
              scope: "admin-all"
      responses:
        "200":
          description: Access token issued
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
              example:
                access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                token_type: "Bearer"
                expires_in: 900
                scope: "admin-all"
        "400":
          description: Invalid grant_type or scope
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                unsupportedGrantType:
                  value:
                    error: "unsupported_grant_type"
                    error_description: "grant_type must be client_credentials"
                invalidScope:
                  value:
                    error: "invalid_scope"
                    error_description: "only admin-all scope is supported by /auth/token"
        "401":
          description: Invalid client credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "invalid_client"
                error_description: "invalid client credentials"
        "429":
          description: Too many failed authentication attempts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "too_many_requests"
                error_description: "too many failed authentication attempts"
        "503":
          description: Authentication service unavailable or disabled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Authentication service is not configured"

  /auth/register:
    post:
      summary: Register a new client
      description: |
        Allows clients to self-register and receive both access and refresh tokens
        for API authentication. This endpoint is optional and typically disabled
        unless explicitly enabled by the solver operator.

        The access token has a short expiry (1 hour by default) and should be included
        in the Authorization header for subsequent API calls. The refresh token has a
        longer expiry (30 days by default) and should be used to obtain new tokens
        when the access token expires.

        If no scopes are provided, the client is granted basic read permissions (read-orders).
        `admin-all` is not allowed on this endpoint.
      operationId: registerClient
      tags:
        - Authentication
      requestBody:
        required: true
        description: Client registration details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
            examples:
              basicRegistration:
                summary: Basic registration with default scopes
                value:
                  client_id: "my-app-client"
                  client_name: "My Application"
              customScopes:
                summary: Registration with custom scopes
                value:
                  client_id: "solver-integration"
                  client_name: "Solver Integration Service"
                  scopes: ["read-orders", "create-orders"]
      responses:
        "201":
          description: Client successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
              example:
                access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                client_id: "my-app-client"
                access_token_expires_at: 1700003600
                refresh_token_expires_at: 1702595600
                scopes: ["read-orders"]
                token_type: "Bearer"
        "400":
          description: Invalid request (empty or invalid client_id, invalid or privileged scopes)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                emptyClientId:
                  value:
                    error: "Client ID cannot be empty"
                invalidClientIdLength:
                  value:
                    error: "Client ID must be between 3 and 100 characters"
                invalidScopes:
                  value:
                    error: "Invalid scopes: Unknown scope: invalid-scope"
                privilegedScope:
                  value:
                    error: "Invalid scopes: admin-all scope is not allowed on /auth/register"
        "403":
          description: Public registration disabled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Public client registration is disabled"
        "500":
          description: Failed to generate tokens (internal server error)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Failed to generate access token"
        "503":
          description: Authentication service not configured
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Authentication service is not configured"

  /auth/refresh:
    post:
      summary: Refresh access token
      description: |
        Exchanges a valid refresh token for new access and refresh tokens.
        This endpoint returns a new refresh token alongside the new access token.

        Use this endpoint when the access token expires (typically after 1 hour)
        to continue making authenticated API calls.
      operationId: refreshToken
      tags:
        - Authentication
      requestBody:
        required: true
        description: Refresh token to exchange
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
            example:
              refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        "200":
          description: Tokens successfully refreshed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
              example:
                access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                client_id: "my-app-client"
                access_token_expires_at: 1700007200
                refresh_token_expires_at: 1702599200
                scopes: ["read-orders"]
                token_type: "Bearer"
        "400":
          description: Invalid request (empty refresh token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Refresh token cannot be empty"
        "401":
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Invalid or expired refresh token"
        "503":
          description: Authentication service not configured
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Authentication service is not configured"

components:
  schemas:
    TokenRequest:
      type: object
      description: Request payload for client credentials token issuance
      required:
        - grant_type
        - client_id
        - client_secret
      properties:
        grant_type:
          type: string
          enum: ["client_credentials"]
          description: Must be `client_credentials`
          example: "client_credentials"
        client_id:
          type: string
          description: Client identifier (used when Basic auth header is not provided)
          example: "solver-admin"
        client_secret:
          type: string
          description: Client secret (used when Basic auth header is not provided)
          example: "replace-with-your-client-secret"
        scope:
          type: string
          description: Requested scope; only `admin-all` is supported
          example: "admin-all"

    TokenResponse:
      type: object
      description: Response payload for successful client credentials token issuance
      required:
        - access_token
        - token_type
        - expires_in
        - scope
      properties:
        access_token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        token_type:
          type: string
          example: "Bearer"
        expires_in:
          type: integer
          description: Token lifetime in seconds
          example: 900
        scope:
          type: string
          example: "admin-all"

    RegisterRequest:
      type: object
      description: Request payload for client registration
      required:
        - client_id
      properties:
        client_id:
          type: string
          minLength: 3
          maxLength: 100
          description: |
            Unique client identifier (e.g., application name, user email, service name).
            Must be between 3 and 100 characters.
          example: "my-app-client"
        client_name:
          type: string
          description: Optional human-readable client name for display purposes
          example: "My Application"
        scopes:
          type: array
          description: |
            Requested scopes for authorization. If not provided, defaults to ["read-orders"].
            Available scopes:
            - read-orders: Read access to order information
            - create-orders: Permission to create new orders
          items:
            type: string
            enum: ["read-orders", "create-orders", "read-quotes", "create-quotes"]
          example: ["read-orders", "create-orders"]

    RefreshRequest:
      type: object
      description: Request payload for token refresh
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          description: The refresh token to exchange for new tokens
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    RegisterResponse:
      type: object
      description: Response payload for successful registration or refresh
      required:
        - access_token
        - refresh_token
        - client_id
        - access_token_expires_at
        - refresh_token_expires_at
        - scopes
        - token_type
      properties:
        access_token:
          type: string
          description: |
            JWT access token for API authentication.
            Include in Authorization header as: `Bearer <access_token>`
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteS1hcHAtY2xpZW50Iiwic2NvcGUiOlsicmVhZC1vcmRlcnMiXSwiZXhwIjoxNzAwMDAzNjAwLCJpYXQiOjE3MDAwMDAwMDAsImlzcyI6Im9pZi1zb2x2ZXIifQ..."
        refresh_token:
          type: string
          description: |
            JWT refresh token for obtaining new access tokens.
            Use with /auth/refresh endpoint when access token expires.
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteS1hcHAtY2xpZW50Iiwic2NvcGUiOlsicmVhZC1vcmRlcnMiXSwiZXhwIjoxNzAyNTk1NjAwLCJpYXQiOjE3MDAwMDAwMDAsImlzcyI6Im9pZi1zb2x2ZXItcmVmcmVzaCJ9..."
        client_id:
          type: string
          description: The client identifier
          example: "my-app-client"
        access_token_expires_at:
          type: integer
          format: int64
          description: Unix timestamp when the access token expires
          example: 1700003600
        refresh_token_expires_at:
          type: integer
          format: int64
          description: Unix timestamp when the refresh token expires
          example: 1702595600
        scopes:
          type: array
          description: Granted scopes for this client
          items:
            type: string
          example: ["read-orders"]
        token_type:
          type: string
          description: Token type (always "Bearer")
          example: "Bearer"

    ErrorResponse:
      type: object
      description: Error response for authentication failures
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Client ID cannot be empty"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token obtained from /auth/token, /auth/register, or /auth/refresh.
        Include in requests as: `Authorization: Bearer <access_token>`

security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: |
      Endpoints for JWT-based authentication and authorization.

      Use these endpoints to obtain and refresh access tokens for protected API endpoints.
      Authentication is optional and configured per solver instance.
