[package]
name = "solver-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
solver-config = { path = "../solver-config" }
solver-types = { path = "../solver-types" }
solver-account = { path = "../solver-account" }

# Async runtime
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# Ethereum
ethers = { version = "2.0", features = ["legacy", "abigen"] }
alloy-primitives = "0.8"
alloy-sol-types = "0.8"

# CLI
clap = { version = "4.5", features = ["derive", "env"] }
colored = "2.1"
comfy-table = "7.1"
indicatif = "0.17"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "ansi",
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = { workspace = true }
base64 = "0.22"
hex = "0.4"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# HTTP
reqwest = { version = "0.12", features = ["json"] }

# JWT
jsonwebtoken = "9.3"
uuid = { version = "1.0", features = ["v4"] }
hostname = "0.4"

# Utils
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
which = "6.0"
nix = { version = "0.29", features = ["process", "signal"] }
futures.workspace = true

# Testing
[dev-dependencies]
tempfile = "3.10"
mockall = "0.13"
