[gas]

[gas.flows.compact_resource_lock]
# Gas units captured by scripts/e2e/estimate_gas_compact.sh
open = 0
fill = 76068
claim = 121995

[gas.flows.permit2_escrow]
# Gas units captured by cast estimate command
open = 141899
fill = 90027 
claim = 75573

[gas.flows.eip3009_escrow]
# Gas units captured
open = 130254
fill = 77298 
claim = 60084