# OIF Solver Configuration - Local Dual-Chain Setup

[solver]
id = "oif-solver-local-dual-chain"
monitoring_timeout_minutes = 5

[storage]
backend = "memory" # or "file"
[storage.config] 
# storage_path = "./data/storage" # Only relevant for "file" backend

[account]
provider = "local"
[account.config]
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[delivery]
min_confirmations = 1
[delivery.providers.origin]
rpc_url = "http://localhost:8545"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
chain_id = 31337

[delivery.providers.destination]
rpc_url = "http://localhost:8546"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
chain_id = 31338

[discovery]
[discovery.sources.onchain_eip7683]
rpc_url = "http://localhost:8545"
settler_addresses = ["0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"]

[discovery.sources.offchain_eip7683]
api_host = "127.0.0.1"
api_port = 8081
rpc_url = "http://localhost:8545"
settler_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
# auth_token = "your-secret-token"

[order]
[order.implementations.eip7683]
output_settler_address = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
input_settler_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
solver_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[order.execution_strategy]
strategy_type = "simple"
[order.execution_strategy.config]
max_gas_price_gwei = 100

[settlement]
[settlement.domain]
# Domain configuration for EIP-712 signatures in quotes
chain_id = 1  # Ethereum mainnet
address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
[settlement.implementations.eip7683]
rpc_url = "http://localhost:8546"
oracle_address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
dispute_period_seconds = 1

# API server configuration
[api]
enabled = true
host = "127.0.0.1"
port = 3000
timeout_seconds = 30
max_request_size = 1048576  # 1MB

# ============================================================================
# DEMO SCRIPT CONFIGURATION
# The following sections are used by demo scripts (send_onchain_intent.sh, etc.)
# and are NOT required by the solver itself. The solver only needs the
# configurations above.
# ============================================================================

# Contract addresses for testing (used by demo scripts)
[contracts.origin]
chain_id = 31337
rpc_url = "http://localhost:8545"
token = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
input_settler = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
the_compact = ""
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
oracle = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[contracts.destination]
chain_id = 31338
rpc_url = "http://localhost:8546"
token = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
output_settler = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Test accounts (used by demo scripts)
[accounts]
solver = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
user = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
user_private_key = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
recipient = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
