# OIF Solver Configuration

[solver]
id = "oif-solver-example"
monitoring_timeout_minutes = 5

# ============================================================================
# NETWORKS - Central configuration for all chains
# ============================================================================
[networks.31337]
rpc_url = "http://localhost:8545"
input_settler_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
output_settler_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
[[networks.31337.tokens]]
address = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
symbol = "TOKA"
decimals = 18
[[networks.31337.tokens]]
address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
symbol = "TOKB"
decimals = 18

[networks.31338]
rpc_url = "http://localhost:8546"
input_settler_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
output_settler_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
[[networks.31338.tokens]]
address = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
symbol = "TOKA"
decimals = 18
[[networks.31338.tokens]]
address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
symbol = "TOKB"
decimals = 18

# ============================================================================
# STORAGE
# ============================================================================
[storage]
primary = "file"
cleanup_interval_seconds = 3600

[storage.implementations.memory]
# Memory storage has no configuration

[storage.implementations.file]
storage_path = "./data/storage"
ttl_orders = 0                  # Permanent
ttl_intents = 86400             # 24 hours
ttl_order_by_tx_hash = 86400    # 24 hours

# ============================================================================
# ACCOUNT
# ============================================================================
[account]
provider = "local"
[account.config]
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# ============================================================================
# DELIVERY - References networks by ID
# ============================================================================
[delivery]
min_confirmations = 1

[delivery.providers.origin]
network_id = 31337  # References networks.31337 for RPC URL and chain ID
# private_key omitted - uses account.config.private_key by default

[delivery.providers.destination]
network_id = 31338  # References networks.31338
# private_key omitted - uses account.config.private_key by default

# Example: Override for specific provider if needed
# [delivery.providers.special]
# network_id = 1
# private_key = "0x..."  # Explicit override for this provider

# ============================================================================
# DISCOVERY - References networks for chain-specific sources
# ============================================================================
[discovery]

[discovery.sources.onchain_eip7683]
network_id = 31337  # Required: specifies which chain to monitor

[discovery.sources.offchain_eip7683]
api_host = "127.0.0.1"
api_port = 8081
network_ids = [31337]  # Optional: declares multi-chain support
# auth_token = "your-secret-token"

# ============================================================================
# ORDER
# ============================================================================
[order]
[order.implementations.eip7683]
# Uses networks config for all chain-specific settings

[order.execution_strategy]
strategy_type = "simple"
[order.execution_strategy.config]
max_gas_price_gwei = 100

# ============================================================================
# SETTLEMENT - References networks for chain config
# ============================================================================
[settlement]
[settlement.domain]
# Domain configuration for EIP-712 signatures in quotes
chain_id = 1  # Ethereum mainnet for signature domain
address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"

[settlement.implementations.eip7683]
network_ids = [31337, 31338]  # Monitor multiple chains for oracle verification
oracle_addresses = { 31337 = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9", 31338 = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9" }
dispute_period_seconds = 1

# ============================================================================
# API SERVER
# ============================================================================
[api]
enabled = true
host = "127.0.0.1"
port = 3000
timeout_seconds = 30
max_request_size = 1048576  # 1MB