# Configuration Production - Mini-Solver Uniswap
# Mode "quote only" - génère des quotes sans exécuter les transactions
# Sans réseaux locaux, uniquement RPCs publics

[solver]
id = "uniswap-mini-solver"
monitoring_timeout_minutes = 5
min_profitability_pct = 1.0

# ============================================================================
# API SERVER - Endpoints HTTP pour les quotes
# ============================================================================
[api]
enabled = true
host = "127.0.0.1"
port = 3002
timeout_seconds = 30
max_request_size = 1048576  # 1MB

[api.implementations]
discovery = "offchain_eip7683"

# Configuration des quotes
[api.quote]
validity_seconds = 60  # 1 minute de validité
allow_unknown_tokens = true

# Configuration Uniswap API (désactivé - utilise V3 on-chain à la place)
[api.quote.uniswap]
enabled = false
slippage_bps = 50  # 0.5% de slippage
# api_key = "YOUR_UNISWAP_API_KEY"  # Optionnel: ou définissez la variable d'env UNISWAP_API_KEY

# Configuration Uniswap V3 on-chain (sans API, via RPC)
[api.quote.uniswap_v3_onchain]
enabled = true
slippage_bps = 50  # 0.5% de slippage
bridge_via_weth = true  # Fallback 2-hop via WETH
default_fees = [500, 3000, 10000]  # Fee tiers à essayer (0.05%, 0.3%, 1%)

# WETH par chain (utilise [[array]] pour HashMap<u64, String>)
[[api.quote.uniswap_v3_onchain.weth]]
chain_id = 1
address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
[[api.quote.uniswap_v3_onchain.weth]]
chain_id = 10
address = "0x4200000000000000000000000000000000000006"
[[api.quote.uniswap_v3_onchain.weth]]
chain_id = 137
address = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
[[api.quote.uniswap_v3_onchain.weth]]
chain_id = 8453
address = "0x4200000000000000000000000000000000000006"
[[api.quote.uniswap_v3_onchain.weth]]
chain_id = 42161
address = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"

# Quoter V2 par chain
[[api.quote.uniswap_v3_onchain.quoter]]
chain_id = 1
address = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
[[api.quote.uniswap_v3_onchain.quoter]]
chain_id = 10
address = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
[[api.quote.uniswap_v3_onchain.quoter]]
chain_id = 137
address = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
[[api.quote.uniswap_v3_onchain.quoter]]
chain_id = 8453
address = "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a"
[[api.quote.uniswap_v3_onchain.quoter]]
chain_id = 42161
address = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"

# SwapRouter par chain
[[api.quote.uniswap_v3_onchain.router]]
chain_id = 1
address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
[[api.quote.uniswap_v3_onchain.router]]
chain_id = 10
address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
[[api.quote.uniswap_v3_onchain.router]]
chain_id = 137
address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
[[api.quote.uniswap_v3_onchain.router]]
chain_id = 8453
address = "0x2626664c2603336E57B271c5C0b26F421741e481"
[[api.quote.uniswap_v3_onchain.router]]
chain_id = 42161
address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"

# ============================================================================
# GAS CONFIGURATION
# ============================================================================
[gas]

[gas.flows.compact_resource_lock]
open = 0
fill = 76068
claim = 121995

[gas.flows.permit2_escrow]
open = 143116
fill = 76068
claim = 59953

[gas.flows.eip3009_escrow]
open = 130254
fill = 77298 
claim = 60084

# ============================================================================
# NETWORKS - Uniquement réseaux publics Ethereum
# ============================================================================

# Ethereum Mainnet
[networks.1]
input_settler_address = "0x0000000000000000000000000000000000000000"
output_settler_address = "0x0000000000000000000000000000000000000000"

[[networks.1.rpc_urls]]
http = "https://ethereum-rpc.publicnode.com"

[[networks.1.tokens]]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"  # USDC
symbol = "USDC"
decimals = 6

[[networks.1.tokens]]
address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"  # USDT
symbol = "USDT"
decimals = 6

[[networks.1.tokens]]
address = "0x6B175474E89094C44Da98b954EedeAC495271d0F"  # DAI
symbol = "DAI"
decimals = 18

[[networks.1.tokens]]
address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"  # WETH
symbol = "WETH"
decimals = 18

[[networks.1.tokens]]
address = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"  # WBTC
symbol = "WBTC"
decimals = 8

[[networks.1.tokens]]
address = "0x514910771AF9Ca656af840dff83E8264EcF986CA"  # LINK
symbol = "LINK"
decimals = 18

[[networks.1.tokens]]
address = "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"  # UNI
symbol = "UNI"
decimals = 18

[[networks.1.tokens]]
address = "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9"  # AAVE
symbol = "AAVE"
decimals = 18

[[networks.1.tokens]]
address = "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"  # WSTETH
symbol = "WSTETH"
decimals = 18

[[networks.1.tokens]]
address = "0xae78736Cd615f374D3085123A210448E74Fc6393"  # RETH
symbol = "RETH"
decimals = 18

[[networks.1.tokens]]
address = "0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32"  # LDO
symbol = "LDO"
decimals = 18

[[networks.1.tokens]]
address = "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2"  # MKR
symbol = "MKR"
decimals = 18

[[networks.1.tokens]]
address = "0xc00e94Cb662C3520282E6f5717214004A7f26888"  # COMP
symbol = "COMP"
decimals = 18

[[networks.1.tokens]]
address = "0xD533a949740bb3306d119CC777fa900bA034cd52"  # CRV
symbol = "CRV"
decimals = 18

# Optimism
[networks.10]
input_settler_address = "0x0000000000000000000000000000000000000000"
output_settler_address = "0x0000000000000000000000000000000000000000"

[[networks.10.rpc_urls]]
http = "https://optimism-rpc.publicnode.com"

[[networks.10.tokens]]
address = "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"  # USDC
symbol = "USDC"
decimals = 6

[[networks.10.tokens]]
address = "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"  # USDT
symbol = "USDT"
decimals = 6

# Polygon
[networks.137]
input_settler_address = "0x0000000000000000000000000000000000000000"
output_settler_address = "0x0000000000000000000000000000000000000000"

[[networks.137.rpc_urls]]
http = "https://polygon-bor-rpc.publicnode.com"

[[networks.137.tokens]]
address = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"  # USDC
symbol = "USDC"
decimals = 6

[[networks.137.tokens]]
address = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"  # USDT
symbol = "USDT"
decimals = 6

# Base
[networks.8453]
input_settler_address = "0x0000000000000000000000000000000000000000"
output_settler_address = "0x0000000000000000000000000000000000000000"

[[networks.8453.rpc_urls]]
http = "https://base-rpc.publicnode.com"

[[networks.8453.tokens]]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"  # USDC
symbol = "USDC"
decimals = 6

# Arbitrum
[networks.42161]
input_settler_address = "0x0000000000000000000000000000000000000000"
output_settler_address = "0x0000000000000000000000000000000000000000"

[[networks.42161.rpc_urls]]
http = "https://arbitrum-one-rpc.publicnode.com"

[[networks.42161.tokens]]
address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"  # USDC
symbol = "USDC"
decimals = 6

[[networks.42161.tokens]]
address = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"  # USDT
symbol = "USDT"
decimals = 6

# ============================================================================
# STORAGE - Requis pour le service
# ============================================================================
[storage]
primary = "memory"  # Stockage en mémoire pour les tests
cleanup_interval_seconds = 60

[storage.implementations.memory]
# Pas de configuration nécessaire

# ============================================================================
# ACCOUNT - Requis mais non utilisé en mode quote-only
# ============================================================================
[account]
primary = "local"

[account.implementations.local]
# Clé privée de test (Anvil account #0 - NE PAS UTILISER EN PRODUCTION)
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# ============================================================================
# PRICING - Pour calculer la profitabilité des quotes
# ============================================================================
[pricing]
primary = "coingecko"  # Utilise des prix temps réel via CoinGecko

[pricing.implementations.coingecko]
# api_key = "VOTRE_CLE_COINGECKO"    # Optionnel: sinon plan gratuit/public
# base_url = "https://api.coingecko.com/api/v3"  # Auto si api_key absente
cache_duration_seconds = 60          # Cache 60s
rate_limit_delay_ms = 1200           # Délai anti rate-limit (pro: ~100ms)

# Mapping symboles vers IDs CoinGecko pour pricing USD
[pricing.implementations.coingecko.token_id_map]
USDC = "usd-coin"
USDT = "tether"
DAI = "dai"
WETH = "ethereum"
WBTC = "wrapped-bitcoin"
LINK = "chainlink"
UNI = "uniswap"
AAVE = "aave"
WSTETH = "lido-staked-ether"
RETH = "rocket-pool-eth"
LDO = "lido-dao"
MKR = "maker"
COMP = "compound-governance-token"
CRV = "curve-dao-token"

# ============================================================================
# DISCOVERY - Configuration minimale (non utilisé en mode quote-only)
# ============================================================================
[discovery]

[discovery.implementations.offchain_eip7683]
api_host = "127.0.0.1"
api_port = 3001
network_ids = [1]

# ============================================================================
# DELIVERY - Requis pour la validation
# ============================================================================
[delivery]
min_confirmations = 1

[delivery.implementations.evm_alloy]
network_ids = [1, 10, 137, 8453, 42161]

# ============================================================================
# ORDER - Requis pour la validation
# ============================================================================
[order]

[order.implementations.eip7683]

[order.strategy]
primary = "simple"

[order.strategy.implementations.simple]
max_gas_price_gwei = 100

# ============================================================================
# SETTLEMENT - Requis pour la validation
# ============================================================================
[settlement]

[settlement.domain]
chain_id = 1
address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"

[settlement.implementations.direct]
order = "eip7683"
network_ids = [1, 10, 137, 8453, 42161]
dispute_period_seconds = 1
oracle_selection_strategy = "First"

[settlement.implementations.direct.oracles]
input = { 1 = [
    "0x0000000000000000000000000000000000000000",
], 10 = [
    "0x0000000000000000000000000000000000000000",
], 137 = [
    "0x0000000000000000000000000000000000000000",
], 8453 = [
    "0x0000000000000000000000000000000000000000",
], 42161 = [
    "0x0000000000000000000000000000000000000000",
] }
output = { 1 = [
    "0x0000000000000000000000000000000000000000",
], 10 = [
    "0x0000000000000000000000000000000000000000",
], 137 = [
    "0x0000000000000000000000000000000000000000",
], 8453 = [
    "0x0000000000000000000000000000000000000000",
], 42161 = [
    "0x0000000000000000000000000000000000000000",
] }

[settlement.implementations.direct.routes]
1 = [10, 137, 8453, 42161]
10 = [1, 137, 8453, 42161]
137 = [1, 10, 8453, 42161]
8453 = [1, 10, 137, 42161]
42161 = [1, 10, 137, 8453]

