# OIF Solver Configuration - Testnet USDC Setup

include = [
    "testnet/networks.toml",
    "testnet/api.toml"
]

[solver]
id = "oif-solver-testnet-usdc"
monitoring_timeout_minutes = 5

# ============================================================================
# STORAGE
# ============================================================================
[storage]
primary = "file"
cleanup_interval_seconds = 3600

[storage.implementations.memory]
# Memory storage has no configuration

[storage.implementations.file]
storage_path = "./data/storage"
ttl_orders = 0                  # Permanent
ttl_intents = 86400             # 24 hours
ttl_order_by_tx_hash = 86400    # 24 hours

# ============================================================================
# ACCOUNT
# ============================================================================
[account]
primary = "local"

[account.implementations.local]
private_key = "${SOLVER_PRIVATE_KEY}"  # Set via environment variable

# ============================================================================
# DELIVERY
# ============================================================================
[delivery]
min_confirmations = 3  # Higher confirmations for testnets

[delivery.implementations.evm_alloy]
network_ids = [17000, 11155420]

# ============================================================================
# DISCOVERY
# ============================================================================
[discovery]

[discovery.implementations.onchain_eip7683]
network_ids = [17000, 11155420]

[discovery.implementations.offchain_eip7683]
api_host = "127.0.0.1"
api_port = 8081
network_ids = [17000]

# ============================================================================
# ORDER
# ============================================================================
[order]

[order.implementations.eip7683]

[order.strategy]
primary = "simple"

[order.strategy.implementations.simple]
max_gas_price_gwei = 100

# ============================================================================
# PRICING
# ============================================================================
[pricing]
primary = "coingecko"

[pricing.implementations.coingecko]
cache_duration_seconds = 60
rate_limit_delay_ms = 1200

# ============================================================================
# SETTLEMENT
# ============================================================================
[settlement]

[settlement.domain]
chain_id = 1
address = "0xaD4874B89BD461685a56013109D3599feCB6B9A0"

[settlement.implementations.direct]
order = "eipXXXX"
network_ids = [17000, 11155420]
dispute_period_seconds = 60
oracle_selection_strategy = "First"

[settlement.implementations.direct.oracles]
input = { 17000 = ["0x46E105e5D62385CF5ec1723fcF5ad58008A8810a"], 11155420 = ["0x46E105e5D62385CF5ec1723fcF5ad58008A8810a"] }
output = { 17000 = ["0x46E105e5D62385CF5ec1723fcF5ad58008A8810a"], 11155420 = ["0x46E105e5D62385CF5ec1723fcF5ad58008A8810a"] }

[settlement.implementations.direct.routes]
17000 = [11155420]
11155420 = [17000]

# ============================================================================
# HYPERLANE SETTLEMENT (For Holesky <-> Optimism Sepolia)
# ============================================================================
[settlement.implementations.hyperlane]
order = "eip7683"
network_ids = [17000, 11155420]
default_gas_limit = 500000
message_timeout_seconds = 600
finalization_required = true

# Oracle addresses - YOU MUST DEPLOY these HyperlaneOracle contracts
[settlement.implementations.hyperlane.oracles]
input = { 17000 = ["0x0b88D54A39F330Dd7e773af4806BDC490c79cAB6"],  11155420 = ["0x0b88D54A39F330Dd7e773af4806BDC490c79cAB6"] }
output = { 17000 = ["0x0b88D54A39F330Dd7e773af4806BDC490c79cAB6"],  11155420 = ["0x0b88D54A39F330Dd7e773af4806BDC490c79cAB6"] }

[settlement.implementations.hyperlane.routes]
17000 = [11155420]
# 11155420 = [17000]

# Official Hyperlane Mailbox addresses
[settlement.implementations.hyperlane.mailboxes]
17000 = "0x46f7C5D896bbeC89bE1B19e4485e59b4Be49e9Cc"
11155420 = "0x6966b0E55883d49BFB24539356a2f8A673E02039"

# Official Hyperlane IGP addresses
[settlement.implementations.hyperlane.igp_addresses]
17000 = "0x5CBf4e70448Ed46c2616b04e9ebc72D29FF0cfA9"
11155420 = "0x28B02B97a850872C4D33C3E024fab6499ad96564"

# ============================================================================
# DEMO SCRIPT CONFIGURATION
# The following sections are used by demo scripts (send_onchain_intent.sh, etc.)
# and are NOT required by the solver itself. The solver only needs the
# configurations above.
# ============================================================================

# Contract addresses for testing (used by demo scripts)
[contracts.origin]
USDC = "0x7dfFC9e7db5a96887666c1a6D215E5d3Fb306d69"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

[contracts.destination]
USDC = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Test accounts (used by demo scripts)
[accounts]
solver = "0xdf2ef67c96DdC136A8447F9eca1959B85C210218"
user = "0x487C810990E17594A2Caa022a1E132c7B94F832f"
user_private_key = "${USER_PRIVATE_KEY}"  # Set via environment variable for demo scripts only
recipient = "0x487C810990E17594A2Caa022a1E132c7B94F832f"
