//! Broadcaster oracle settlement implementation.
//!
//! This settlement uses BroadcasterOracle `submit` + `verifyMessage` flow and
//! relies on storage proofs generated by an external prover service.

use crate::{
	utils::{
		address_to_bytes32, check_is_proven, create_providers_for_chains, parse_address_table,
		parse_b256_table, parse_oracle_config, SettlementMessageTracker,
	},
	OracleConfig, PusherDirection, SettlementError, SettlementInterface,
};
use alloy_primitives::{hex, FixedBytes, B256, U256};
use alloy_provider::{DynProvider, Provider};
use alloy_sol_types::{sol, SolCall};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use sha3::{Digest, Keccak256};
use solver_storage::StorageService;
use solver_types::{
	with_0x_prefix, ConfigSchema, Field, FieldType, FillProof, InteropAddress, NetworksConfig,
	Order, OrderOutput, PusherL2Params, Schema, Transaction, TransactionHash, TransactionReceipt,
	TransactionType,
};
use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

sol! {
	struct RemoteReadArgs {
		address[] route;
		bytes[] bhpInputs;
		bytes storageProof;
	}

	interface IBroadcasterOracle {
		function submit(address source, bytes[] calldata payloads) external;

		function verifyMessage(
			RemoteReadArgs calldata broadcasterReadArgs,
			uint256 remoteChainId,
			address remoteOracle,
			bytes calldata messageData
		) external;
	}

	event MessageBroadcast(bytes32 indexed message, address indexed publisher);
}

fn now_seconds() -> u64 {
	SystemTime::now()
		.duration_since(UNIX_EPOCH)
		.map(|d| d.as_secs())
		.unwrap_or(0)
}

/// Helper to compute keccak256 hash.
fn keccak256(data: &[u8]) -> [u8; 32] {
	let mut hasher = Keccak256::new();
	hasher.update(data);
	let result = hasher.finalize();
	let mut out = [0u8; 32];
	out.copy_from_slice(&result);
	out
}

/// Convert order ID string to bytes32.
fn order_id_to_bytes32(order_id: &str) -> [u8; 32] {
	if let Some(hex_str) = order_id.strip_prefix("0x") {
		let mut bytes = [0u8; 32];
		if let Ok(decoded) = hex::decode(hex_str) {
			let len = decoded.len().min(32);
			bytes[32 - len..].copy_from_slice(&decoded[..len]);
		}
		bytes
	} else {
		let raw = order_id.as_bytes();
		let mut bytes = [0u8; 32];
		let len = raw.len().min(32);
		bytes[32 - len..].copy_from_slice(&raw[..len]);
		bytes
	}
}

/// Broadcaster-compatible output representation.
struct EncodedOutput {
	token: [u8; 32],
	amount: U256,
	recipient: [u8; 32],
	call: Vec<u8>,
	context: Vec<u8>,
}

fn interop_address_to_bytes32(addr: &InteropAddress) -> [u8; 32] {
	let mut bytes32 = [0u8; 32];
	let raw_bytes = addr.to_bytes();

	if let Ok(eth_addr) = addr.ethereum_address() {
		bytes32[12..].copy_from_slice(eth_addr.as_slice());
	} else {
		let len = raw_bytes.len().min(32);
		bytes32[32 - len..].copy_from_slice(&raw_bytes[..len]);
	}

	bytes32
}

fn order_output_to_encoded(output: &OrderOutput) -> EncodedOutput {
	EncodedOutput {
		token: interop_address_to_bytes32(&output.asset),
		amount: output.amount,
		recipient: interop_address_to_bytes32(&output.receiver),
		call: output
			.calldata
			.as_ref()
			.and_then(|s| hex::decode(s.trim_start_matches("0x")).ok())
			.unwrap_or_default(),
		context: vec![],
	}
}

fn extract_output_details(order: &Order) -> Result<EncodedOutput, SettlementError> {
	let parsed_order = order.parse_order_data().map_err(|e| {
		SettlementError::ValidationFailed(format!("Failed to parse order data: {e}"))
	})?;
	let outputs = parsed_order.parse_requested_outputs();
	let first_output = outputs
		.first()
		.ok_or_else(|| SettlementError::ValidationFailed("No outputs found in order".into()))?;
	Ok(order_output_to_encoded(first_output))
}

/// Extract (solver, timestamp) from OutputFilled logs.
fn extract_fill_details_from_logs(
	logs: &[solver_types::Log],
	order_id: &[u8; 32],
) -> Result<([u8; 32], u32), SettlementError> {
	let output_filled_signature = keccak256(
		b"OutputFilled(bytes32,bytes32,uint32,(bytes32,bytes32,uint256,bytes32,uint256,bytes32,bytes,bytes),uint256)",
	);

	for log in logs {
		if log.topics.len() >= 2
			&& log.topics[0].0 == output_filled_signature
			&& log.topics[1].0 == *order_id
			&& log.data.len() >= 64
		{
			let mut solver = [0u8; 32];
			solver.copy_from_slice(&log.data[0..32]);
			let timestamp_bytes = &log.data[32..64];
			let timestamp = u32::from_be_bytes([
				timestamp_bytes[28],
				timestamp_bytes[29],
				timestamp_bytes[30],
				timestamp_bytes[31],
			]);
			return Ok((solver, timestamp));
		}
	}

	Err(SettlementError::ValidationFailed(
		"No OutputFilled event detected in logs".into(),
	))
}

#[allow(clippy::too_many_arguments)]
fn encode_fill_description(
	solver_identifier: [u8; 32],
	order_id: [u8; 32],
	timestamp: u32,
	token: [u8; 32],
	amount: U256,
	recipient: [u8; 32],
	call_data: Vec<u8>,
	context: Vec<u8>,
) -> Result<Vec<u8>, SettlementError> {
	if call_data.len() > u16::MAX as usize {
		return Err(SettlementError::ValidationFailed(
			"Call data too large".into(),
		));
	}
	if context.len() > u16::MAX as usize {
		return Err(SettlementError::ValidationFailed(
			"Context data too large".into(),
		));
	}

	let mut payload =
		Vec::with_capacity(32 + 32 + 4 + 32 + 32 + 32 + 2 + call_data.len() + 2 + context.len());
	payload.extend_from_slice(&solver_identifier);
	payload.extend_from_slice(&order_id);
	payload.extend_from_slice(&timestamp.to_be_bytes());
	payload.extend_from_slice(&token);
	payload.extend_from_slice(&amount.to_be_bytes::<32>());
	payload.extend_from_slice(&recipient);
	payload.extend_from_slice(&(call_data.len() as u16).to_be_bytes());
	payload.extend_from_slice(&call_data);
	payload.extend_from_slice(&(context.len() as u16).to_be_bytes());
	payload.extend_from_slice(&context);
	Ok(payload)
}

fn encode_message_data(
	application: [u8; 32],
	payloads: &[Vec<u8>],
) -> Result<Vec<u8>, SettlementError> {
	if payloads.len() > u16::MAX as usize {
		return Err(SettlementError::ValidationFailed(
			"Too many payloads for message encoding".into(),
		));
	}

	let mut encoded = Vec::new();
	encoded.extend_from_slice(&application);
	encoded.extend_from_slice(&(payloads.len() as u16).to_be_bytes());

	for payload in payloads {
		if payload.len() > u16::MAX as usize {
			return Err(SettlementError::ValidationFailed(
				"Payload too large for message encoding".into(),
			));
		}
		encoded.extend_from_slice(&(payload.len() as u16).to_be_bytes());
		encoded.extend_from_slice(payload);
	}

	Ok(encoded)
}

fn hash_payload_hashes(payload_hashes: &[[u8; 32]]) -> [u8; 32] {
	let mut bytes = Vec::with_capacity(payload_hashes.len() * 32);
	for payload_hash in payload_hashes {
		bytes.extend_from_slice(payload_hash);
	}
	keccak256(&bytes)
}

fn compute_broadcaster_message(source: &solver_types::Address, payloads: &[Vec<u8>]) -> [u8; 32] {
	let payload_hashes: Vec<[u8; 32]> = payloads.iter().map(|payload| keccak256(payload)).collect();
	let payload_hashes_digest = hash_payload_hashes(&payload_hashes);

	// keccak256(abi.encode(address, bytes32))
	// Guard: only copy if address is exactly 20 bytes; zero-pad otherwise.
	let mut encoded = [0u8; 64];
	if source.0.len() == 20 {
		encoded[12..32].copy_from_slice(&source.0);
	}
	encoded[32..64].copy_from_slice(&payload_hashes_digest);
	keccak256(&encoded)
}

fn compute_message_slot(message: [u8; 32], publisher: &solver_types::Address) -> [u8; 32] {
	// keccak256(abi.encode(message, publisher))
	// Guard: only copy if address is exactly 20 bytes; zero-pad otherwise.
	let mut encoded = [0u8; 64];
	encoded[0..32].copy_from_slice(&message);
	if publisher.0.len() == 20 {
		encoded[44..64].copy_from_slice(&publisher.0);
	}
	keccak256(&encoded)
}

fn parse_hex_bytes(label: &str, value: &str) -> Result<Vec<u8>, SettlementError> {
	hex::decode(value.trim_start_matches("0x"))
		.map_err(|e| SettlementError::ValidationFailed(format!("Invalid hex for {label}: {e}")))
}

fn parse_u64_table(table: &toml::Value) -> Result<HashMap<u64, u64>, SettlementError> {
	let mut result = HashMap::new();
	if let Some(table) = table.as_table() {
		for (chain_id_str, value) in table {
			let chain_id = chain_id_str.parse::<u64>().map_err(|e| {
				SettlementError::ValidationFailed(format!("Invalid chain ID '{chain_id_str}': {e}"))
			})?;
			let raw_value = value.as_integer().ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"Integer value required for chain {chain_id}"
				))
			})?;
			if raw_value < 0 {
				return Err(SettlementError::ValidationFailed(format!(
					"Integer value must be non-negative for chain {chain_id}"
				)));
			}
			result.insert(chain_id, raw_value as u64);
		}
	}
	Ok(result)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct BroadcasterSubmission {
	source_chain: u64,
	destination_chain: u64,
	submission_tx_hash: TransactionHash,
	submission_timestamp: u64,
	/// Block number on destination chain where the message was broadcast (PostFill tx block)
	#[serde(default)]
	submission_block_number: Option<u64>,
	#[serde(with = "hex::serde")]
	payload_hash: [u8; 32],
	#[serde(with = "hex::serde")]
	message: [u8; 32],
	message_data: Vec<u8>,
	application: solver_types::Address,
	remote_oracle: solver_types::Address,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct BroadcasterProofData {
	route: Vec<solver_types::Address>,
	bhp_inputs: Vec<Vec<u8>>,
	storage_proof: Vec<u8>,
	generated_at: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct VerifiedMessage {
	verified_at: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct BroadcasterMessageState {
	submission: Option<BroadcasterSubmission>,
	proof: Option<BroadcasterProofData>,
	verified: Option<VerifiedMessage>,
}

#[derive(Clone)]
struct BroadcasterMessageTracker {
	tracker: SettlementMessageTracker<BroadcasterMessageState>,
}

impl BroadcasterMessageTracker {
	fn new(storage: Arc<StorageService>) -> Self {
		Self {
			tracker: SettlementMessageTracker::new(storage, "broadcaster"),
		}
	}

	async fn load(
		&self,
		order_id: &str,
	) -> Result<Option<BroadcasterMessageState>, SettlementError> {
		self.tracker.load(order_id).await
	}

	async fn save(
		&self,
		order_id: &str,
		state: &BroadcasterMessageState,
	) -> Result<(), SettlementError> {
		let ttl = if state.verified.is_some() {
			Some(Duration::from_secs(7 * 24 * 60 * 60))
		} else {
			None
		};
		self.tracker.save(order_id, state, ttl).await
	}

	async fn track_submission(
		&self,
		order_id: &str,
		submission: BroadcasterSubmission,
	) -> Result<(), SettlementError> {
		let mut state = self
			.load(order_id)
			.await
			.map_err(|e| {
				SettlementError::ValidationFailed(format!(
					"Failed to load broadcaster submission state for order {order_id}: {e}"
				))
			})?
			.unwrap_or(BroadcasterMessageState {
				submission: None,
				proof: None,
				verified: None,
			});
		state.submission = Some(submission);
		state.proof = None;
		self.save(order_id, &state).await
	}

	async fn store_proof(
		&self,
		order_id: &str,
		proof: BroadcasterProofData,
	) -> Result<(), SettlementError> {
		let mut state = self
			.load(order_id)
			.await
			.map_err(|e| {
				SettlementError::ValidationFailed(format!(
					"Failed to load broadcaster proof state for order {order_id}: {e}"
				))
			})?
			.unwrap_or(BroadcasterMessageState {
				submission: None,
				proof: None,
				verified: None,
			});
		state.proof = Some(proof);
		self.save(order_id, &state).await
	}

	async fn mark_verified(&self, order_id: &str) -> Result<(), SettlementError> {
		let mut state = self
			.load(order_id)
			.await
			.map_err(|e| {
				SettlementError::ValidationFailed(format!(
					"Failed to load broadcaster verification state for order {order_id}: {e}"
				))
			})?
			.unwrap_or(BroadcasterMessageState {
				submission: None,
				proof: None,
				verified: None,
			});
		state.verified = Some(VerifiedMessage {
			verified_at: now_seconds(),
		});
		self.save(order_id, &state).await
	}
}

#[derive(Debug, Serialize)]
struct ProofRequest {
	remote_chain_id: u64,
	local_chain_id: u64,
	broadcaster_address: String,
	receiver_address: String,
	publisher: String,
	message: String,
	message_slot: String,
	broadcaster_id: String,
	/// Minimum block number on remote chain that the proof must cover (PostFill tx block)
	#[serde(skip_serializing_if = "Option::is_none")]
	min_remote_block: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct ProofResponse {
	route: Vec<String>,
	#[serde(alias = "bhpInputs")]
	bhp_inputs: Vec<String>,
	#[serde(alias = "storageProof")]
	storage_proof: String,
}

/// Broadcaster settlement implementation.
pub struct BroadcasterSettlement {
	providers: HashMap<u64, DynProvider>,
	oracle_config: OracleConfig,
	broadcaster_addresses: HashMap<u64, solver_types::Address>,
	receiver_addresses: HashMap<u64, solver_types::Address>,
	broadcaster_ids: HashMap<u64, B256>,
	proof_service_url: String,
	proof_wait_time_seconds: u64,
	storage_proof_timeout_seconds: u64,
	default_finality_blocks: u64,
	finality_blocks: HashMap<u64, u64>,
	message_tracker: Arc<BroadcasterMessageTracker>,
	http_client: reqwest::Client,
	pusher_directions: Vec<PusherDirection>,
}

impl BroadcasterSettlement {
	#[allow(clippy::too_many_arguments)]
	pub fn new(
		networks: &NetworksConfig,
		oracle_config: OracleConfig,
		broadcaster_addresses: HashMap<u64, solver_types::Address>,
		receiver_addresses: HashMap<u64, solver_types::Address>,
		broadcaster_ids: HashMap<u64, B256>,
		proof_service_url: String,
		proof_wait_time_seconds: u64,
		storage_proof_timeout_seconds: u64,
		default_finality_blocks: u64,
		finality_blocks: HashMap<u64, u64>,
		storage: Arc<StorageService>,
		pusher_directions: Vec<PusherDirection>,
	) -> Result<Self, SettlementError> {
		let mut all_network_ids: Vec<u64> = oracle_config
			.input_oracles
			.keys()
			.chain(oracle_config.output_oracles.keys())
			.copied()
			.collect();

		for chain_id in broadcaster_addresses.keys() {
			all_network_ids.push(*chain_id);
		}
		for chain_id in receiver_addresses.keys() {
			all_network_ids.push(*chain_id);
		}

		let providers = create_providers_for_chains(&all_network_ids, networks)?;

		// Validate broadcaster config coverage for configured routes.
		for (source_chain, destination_chains) in &oracle_config.routes {
			if !receiver_addresses.contains_key(source_chain) {
				return Err(SettlementError::ValidationFailed(format!(
					"Receiver address not configured for source chain {source_chain}"
				)));
			}

			for destination_chain in destination_chains {
				if !broadcaster_addresses.contains_key(destination_chain) {
					return Err(SettlementError::ValidationFailed(format!(
						"Broadcaster address not configured for destination chain {destination_chain}"
					)));
				}
				if !broadcaster_ids.contains_key(destination_chain) {
					return Err(SettlementError::ValidationFailed(format!(
						"Broadcaster ID not configured for remote chain {destination_chain}"
					)));
				}
			}
		}

		let http_client = reqwest::Client::builder()
			.timeout(Duration::from_secs(storage_proof_timeout_seconds))
			.build()
			.map_err(|e| {
				SettlementError::ValidationFailed(format!("Failed to build HTTP client: {e}"))
			})?;

		Ok(Self {
			providers,
			oracle_config,
			broadcaster_addresses,
			receiver_addresses,
			broadcaster_ids,
			proof_service_url,
			proof_wait_time_seconds,
			storage_proof_timeout_seconds,
			default_finality_blocks,
			finality_blocks,
			message_tracker: Arc::new(BroadcasterMessageTracker::new(storage)),
			http_client,
			pusher_directions,
		})
	}

	fn source_and_destination_chain(order: &Order) -> Result<(u64, u64), SettlementError> {
		let source_chain = order
			.input_chains
			.first()
			.map(|c| c.chain_id)
			.ok_or_else(|| SettlementError::ValidationFailed("No input chains in order".into()))?;
		let destination_chain = order
			.output_chains
			.first()
			.map(|c| c.chain_id)
			.ok_or_else(|| SettlementError::ValidationFailed("No output chains in order".into()))?;
		Ok((source_chain, destination_chain))
	}

	fn finality_blocks_for(&self, chain_id: u64) -> u64 {
		self.finality_blocks
			.get(&chain_id)
			.copied()
			.unwrap_or(self.default_finality_blocks)
	}

	fn proof_endpoint(&self) -> String {
		format!(
			"{}/api/v1/broadcaster/proof",
			self.proof_service_url.trim_end_matches('/')
		)
	}

	fn parse_fill_payload_from_logs(
		&self,
		order: &Order,
		logs: &[solver_types::Log],
	) -> Result<Vec<u8>, SettlementError> {
		let output = extract_output_details(order)?;
		let order_id_bytes = order_id_to_bytes32(&order.id);
		let (solver_identifier, fill_timestamp) =
			extract_fill_details_from_logs(logs, &order_id_bytes)?;

		encode_fill_description(
			solver_identifier,
			order_id_bytes,
			fill_timestamp,
			output.token,
			output.amount,
			output.recipient,
			output.call,
			output.context,
		)
	}

	async fn fetch_fill_receipt_logs(
		&self,
		order: &Order,
		destination_chain: u64,
	) -> Result<Vec<solver_types::Log>, SettlementError> {
		let fill_tx_hash = order.fill_tx_hash.as_ref().ok_or_else(|| {
			SettlementError::ValidationFailed(
				"Missing fill transaction hash: required for broadcaster payload tracking".into(),
			)
		})?;

		let provider = self.providers.get(&destination_chain).ok_or_else(|| {
			SettlementError::ValidationFailed(format!("No provider for chain {destination_chain}"))
		})?;

		let receipt = provider
			.get_transaction_receipt(FixedBytes::<32>::from_slice(&fill_tx_hash.0))
			.await
			.map_err(|e| {
				SettlementError::ValidationFailed(format!("Failed to get fill receipt: {e}"))
			})?
			.ok_or_else(|| {
				SettlementError::ValidationFailed("Fill transaction not found".to_string())
			})?;

		let logs: Vec<solver_types::Log> = receipt
			.inner
			.logs()
			.iter()
			.map(|log| solver_types::Log {
				address: solver_types::Address(log.address().0 .0.to_vec()),
				topics: log
					.topics()
					.iter()
					.map(|topic| solver_types::H256(topic.0))
					.collect(),
				data: log.data().data.to_vec(),
			})
			.collect();

		Ok(logs)
	}

	fn extract_message_from_broadcast_logs(
		&self,
		logs: &[solver_types::Log],
		expected_publisher: &solver_types::Address,
	) -> Option<[u8; 32]> {
		let signature = keccak256(b"MessageBroadcast(bytes32,address)");
		for log in logs {
			if log.topics.len() < 3 {
				continue;
			}
			if log.topics[0].0 != signature {
				continue;
			}

			let publisher_topic = log.topics[2].0;
			let publisher = solver_types::Address(publisher_topic[12..].to_vec());
			if &publisher == expected_publisher {
				return Some(log.topics[1].0);
			}
		}
		None
	}

	async fn generate_and_store_proof(
		&self,
		order: &Order,
		source_chain: u64,
		destination_chain: u64,
		submission: &BroadcasterSubmission,
	) -> Result<(), SettlementError> {
		let broadcaster_address = self
			.broadcaster_addresses
			.get(&destination_chain)
			.ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"No broadcaster configured for chain {destination_chain}"
				))
			})?;

		let receiver_address = self.receiver_addresses.get(&source_chain).ok_or_else(|| {
			SettlementError::ValidationFailed(format!(
				"No receiver configured for chain {source_chain}"
			))
		})?;

		let broadcaster_id = self
			.broadcaster_ids
			.get(&destination_chain)
			.ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"No broadcaster ID configured for chain {destination_chain}"
				))
			})?;

		let message_slot = compute_message_slot(submission.message, &submission.remote_oracle);

		let request_payload = ProofRequest {
			remote_chain_id: destination_chain,
			local_chain_id: source_chain,
			broadcaster_address: with_0x_prefix(&hex::encode(&broadcaster_address.0)),
			receiver_address: with_0x_prefix(&hex::encode(&receiver_address.0)),
			publisher: with_0x_prefix(&hex::encode(&submission.remote_oracle.0)),
			message: with_0x_prefix(&hex::encode(submission.message)),
			message_slot: with_0x_prefix(&hex::encode(message_slot)),
			broadcaster_id: broadcaster_id.to_string(),
			min_remote_block: submission.submission_block_number,
		};

		let response = self
			.http_client
			.post(self.proof_endpoint())
			.json(&request_payload)
			.send()
			.await
			.map_err(|e| SettlementError::ProofGenerationFailed {
				source_chain: destination_chain,
				reason: format!("proof service request failed: {e}"),
			})?;

		if !response.status().is_success() {
			let status = response.status();
			let body = response.text().await.unwrap_or_default();
			return Err(SettlementError::ProofGenerationFailed {
				source_chain: destination_chain,
				reason: format!("proof service returned {status}: {body}"),
			});
		}

		let proof_response: ProofResponse =
			response
				.json()
				.await
				.map_err(|e| SettlementError::ProofGenerationFailed {
					source_chain: destination_chain,
					reason: format!("invalid proof response payload: {e}"),
				})?;

		let route: Vec<solver_types::Address> = proof_response
			.route
			.iter()
			.map(|address| {
				solver_types::utils::parse_address(address).map_err(|e| {
					SettlementError::ProofGenerationFailed {
						source_chain: destination_chain,
						reason: format!("invalid route address '{address}': {e}"),
					}
				})
			})
			.collect::<Result<_, _>>()?;

		let bhp_inputs: Vec<Vec<u8>> = proof_response
			.bhp_inputs
			.iter()
			.map(|value| {
				parse_hex_bytes("bhp_inputs", value).map_err(|e| {
					SettlementError::ProofGenerationFailed {
						source_chain: destination_chain,
						reason: e.to_string(),
					}
				})
			})
			.collect::<Result<_, _>>()?;

		let storage_proof = parse_hex_bytes("storage_proof", &proof_response.storage_proof)
			.map_err(|e| SettlementError::ProofGenerationFailed {
				source_chain: destination_chain,
				reason: e.to_string(),
			})?;

		if route.is_empty() || route.len() != bhp_inputs.len() {
			return Err(SettlementError::ProofGenerationFailed {
				source_chain: destination_chain,
				reason: "route/bhp_inputs length mismatch".into(),
			});
		}

		self.message_tracker
			.store_proof(
				&order.id,
				BroadcasterProofData {
					route,
					bhp_inputs,
					storage_proof,
					generated_at: now_seconds(),
				},
			)
			.await
	}
}

/// Configuration schema for broadcaster settlement.
pub struct BroadcasterSettlementSchema;

impl BroadcasterSettlementSchema {
	pub fn validate_config(config: &toml::Value) -> Result<(), solver_types::ValidationError> {
		let instance = Self;
		instance.validate(config)
	}
}

impl ConfigSchema for BroadcasterSettlementSchema {
	fn validate(&self, config: &toml::Value) -> Result<(), solver_types::ValidationError> {
		let schema = Schema::new(
			vec![
				Field::new(
					"oracles",
					FieldType::Table(Schema::new(
						vec![
							Field::new("input", FieldType::Table(Schema::new(vec![], vec![]))),
							Field::new("output", FieldType::Table(Schema::new(vec![], vec![]))),
						],
						vec![],
					)),
				),
				Field::new("routes", FieldType::Table(Schema::new(vec![], vec![]))),
				Field::new(
					"broadcaster_addresses",
					FieldType::Table(Schema::new(vec![], vec![])),
				),
				Field::new(
					"receiver_addresses",
					FieldType::Table(Schema::new(vec![], vec![])),
				),
				Field::new(
					"broadcaster_ids",
					FieldType::Table(Schema::new(vec![], vec![])),
				),
				Field::new("proof_service_url", FieldType::String),
			],
			vec![
				Field::new("oracle_selection_strategy", FieldType::String),
				Field::new(
					"proof_wait_time_seconds",
					FieldType::Integer {
						min: Some(0),
						max: Some(3600),
					},
				),
				Field::new(
					"storage_proof_timeout_seconds",
					FieldType::Integer {
						min: Some(1),
						max: Some(300),
					},
				),
				Field::new(
					"default_finality_blocks",
					FieldType::Integer {
						min: Some(1),
						max: Some(10000),
					},
				),
				Field::new(
					"finality_blocks",
					FieldType::Table(Schema::new(vec![], vec![])),
				),
				Field::new(
					"chain_block_time_seconds",
					FieldType::Table(Schema::new(vec![], vec![])),
				),
				Field::new(
					"intent_safety_buffer_seconds",
					FieldType::Integer {
						min: Some(0),
						max: Some(3600),
					},
				),
				Field::new(
					"intent_min_expiry_seconds",
					FieldType::Integer {
						min: Some(0),
						max: Some(86400),
					},
				),
				// Sub-field validation is intentionally skipped here; it is performed
				// inside parse_pusher_directions() after the schema check passes.
				Field::new(
					"pusher_directions",
					FieldType::Array(Box::new(FieldType::Table(Schema::new(vec![], vec![])))),
				),
			],
		);
		schema.validate(config)
	}
}

#[async_trait]
impl SettlementInterface for BroadcasterSettlement {
	fn oracle_config(&self) -> &OracleConfig {
		&self.oracle_config
	}

	fn config_schema(&self) -> Box<dyn ConfigSchema> {
		Box::new(BroadcasterSettlementSchema)
	}

	async fn buffer_coverage_check(&self, order: &Order) -> Option<(PusherDirection, u64)> {
		// load() returns Option<BroadcasterMessageState> — None means no submission yet.
		let state = match self.message_tracker.load(&order.id).await {
			Ok(Some(state)) => state,
			Ok(None) => return None,
			Err(e) => {
				tracing::warn!(order_id = %order.id, error = %e, "Failed to load broadcaster state");
				return None;
			},
		};
		let submission = state.submission?;
		let required_block = submission.submission_block_number?;
		// Fill chain = destination_chain (where the PostFill broadcast was confirmed).
		// Claim chain = source_chain (where the receiver oracle lives).
		let direction = self.pusher_directions.iter().find(|d| {
			d.l1_chain_id == submission.destination_chain
				&& d.l2_chain_id == submission.source_chain
		})?;
		Some((direction.clone(), required_block))
	}

	async fn get_attestation(
		&self,
		order: &Order,
		tx_hash: &TransactionHash,
	) -> Result<FillProof, SettlementError> {
		let (source_chain, destination_chain) = Self::source_and_destination_chain(order)?;
		let provider = self.providers.get(&destination_chain).ok_or_else(|| {
			SettlementError::ValidationFailed(format!(
				"No provider configured for chain {destination_chain}"
			))
		})?;

		let oracle_addresses = self.get_input_oracles(source_chain);
		if oracle_addresses.is_empty() {
			return Err(SettlementError::ValidationFailed(format!(
				"No input oracle configured for chain {source_chain}"
			)));
		}

		let order_id_hash = keccak256(order.id.as_bytes());
		let selection_context =
			u64::from_be_bytes(order_id_hash[0..8].try_into().map_err(|_| {
				SettlementError::ValidationFailed("Failed to convert hash bytes".to_string())
			})?);
		let oracle_address = self
			.select_oracle(&oracle_addresses, Some(selection_context))
			.ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"Failed to select oracle for chain {source_chain}"
				))
			})?;

		let receipt = provider
			.get_transaction_receipt(FixedBytes::<32>::from_slice(&tx_hash.0))
			.await
			.map_err(|e| SettlementError::ValidationFailed(format!("Failed to get receipt: {e}")))?
			.ok_or_else(|| {
				SettlementError::ValidationFailed("Transaction not found".to_string())
			})?;

		if !receipt.status() {
			return Err(SettlementError::ValidationFailed(
				"Transaction failed".to_string(),
			));
		}

		let tx_block = receipt.block_number.unwrap_or(0);
		let block = provider
			.get_block_by_number(alloy_rpc_types::BlockNumberOrTag::Number(tx_block))
			.await
			.map_err(|e| SettlementError::ValidationFailed(format!("Failed to get block: {e}")))?;

		let block_timestamp = block
			.ok_or_else(|| SettlementError::ValidationFailed("Block not found".to_string()))?
			.header
			.timestamp;

		Ok(FillProof {
			tx_hash: tx_hash.clone(),
			block_number: tx_block,
			oracle_address: with_0x_prefix(&hex::encode(&oracle_address.0)),
			attestation_data: None,
			filled_timestamp: block_timestamp,
		})
	}

	async fn can_claim(&self, order: &Order, fill_proof: &FillProof) -> bool {
		let (source_chain, destination_chain) = match Self::source_and_destination_chain(order) {
			Ok(chains) => chains,
			Err(e) => {
				tracing::error!(order_id = %order.id, error = %e, "Invalid order chains");
				return false;
			},
		};

		let state = match self.message_tracker.load(&order.id).await {
			Ok(Some(state)) => state,
			Ok(None) => {
				tracing::debug!(order_id = %order.id, "No broadcaster submission state yet");
				return false;
			},
			Err(e) => {
				tracing::warn!(order_id = %order.id, error = %e, "Failed to load broadcaster state");
				return false;
			},
		};

		let submission = match state.submission.as_ref() {
			Some(submission) => submission,
			None => return false,
		};

		let input_oracle = match self.select_oracle(&self.get_input_oracles(source_chain), None) {
			Some(oracle) => oracle,
			None => return false,
		};
		let output_oracle =
			match self.select_oracle(&self.get_output_oracles(destination_chain), None) {
				Some(oracle) => oracle,
				None => return false,
			};

		let provider = match self.providers.get(&source_chain) {
			Some(provider) => provider,
			None => return false,
		};

		let remote_oracle = address_to_bytes32(&output_oracle);
		let application = address_to_bytes32(&submission.application);
		let is_proven = match check_is_proven(
			provider,
			&input_oracle,
			destination_chain,
			remote_oracle,
			application,
			submission.payload_hash,
		)
		.await
		{
			Ok(proven) => proven,
			Err(e) => {
				tracing::debug!(order_id = %order.id, error = %e, "isProven check failed");
				return false;
			},
		};

		if is_proven {
			if let Err(e) = self.message_tracker.mark_verified(&order.id).await {
				tracing::warn!(order_id = %order.id, error = %e, "Failed to persist verified status");
			}
			return true;
		}

		// Wait a minimum time before proof generation.
		let now = now_seconds();
		if now
			< fill_proof
				.filled_timestamp
				.saturating_add(self.proof_wait_time_seconds)
		{
			return false;
		}

		// Wait for chain finality before generating proofs.
		let destination_provider = match self.providers.get(&destination_chain) {
			Some(provider) => provider,
			None => return false,
		};
		let current_destination_block = match destination_provider.get_block_number().await {
			Ok(block) => block,
			Err(_) => return false,
		};
		let required_finality_block = fill_proof
			.block_number
			.saturating_add(self.finality_blocks_for(destination_chain));
		if current_destination_block < required_finality_block {
			return false;
		}

		// Proof already available and ready to submit.
		if state.proof.is_some() {
			return true;
		}

		// Try proof generation in the monitor loop; return false if unavailable so we retry.
		match self
			.generate_and_store_proof(order, source_chain, destination_chain, submission)
			.await
		{
			Ok(_) => true,
			Err(e) => {
				tracing::warn!(
					order_id = %order.id,
					error = %e,
					timeout_secs = self.storage_proof_timeout_seconds,
					"Broadcaster proof generation not ready"
				);
				false
			},
		}
	}

	async fn generate_post_fill_transaction(
		&self,
		order: &Order,
		fill_receipt: &TransactionReceipt,
	) -> Result<Option<Transaction>, SettlementError> {
		let (_, destination_chain) = Self::source_and_destination_chain(order)?;

		let output_oracles = self.get_output_oracles(destination_chain);
		if output_oracles.is_empty() {
			return Ok(None);
		}
		// Derive a deterministic selection context from the order ID so that
		// RoundRobin/Random strategies pick the same oracle for the same order
		// across retries (avoids non-deterministic post-fill routing).
		let oracle_hint = {
			let hash = keccak256(order.id.as_bytes());
			let mut buf = [0u8; 8];
			buf.copy_from_slice(&hash[..8]);
			u64::from_be_bytes(buf)
		};
		let output_oracle = self
			.select_oracle(&output_oracles, Some(oracle_hint))
			.ok_or_else(|| SettlementError::ValidationFailed("Failed to select oracle".into()))?;

		let output_settler = order
			.output_chains
			.first()
			.ok_or_else(|| SettlementError::ValidationFailed("No output chain".into()))?
			.settler_address
			.clone();

		let fill_payload = self.parse_fill_payload_from_logs(order, &fill_receipt.logs)?;
		let payloads = vec![fill_payload];

		let call_data = IBroadcasterOracle::submitCall {
			source: alloy_primitives::Address::from_slice(&output_settler.0),
			payloads: payloads.into_iter().map(Into::into).collect(),
		};

		Ok(Some(Transaction {
			to: Some(output_oracle),
			data: call_data.abi_encode(),
			value: U256::ZERO,
			chain_id: destination_chain,
			nonce: None,
			gas_limit: Some(500000),
			gas_price: None,
			max_fee_per_gas: None,
			max_priority_fee_per_gas: None,
		}))
	}

	async fn generate_pre_claim_transaction(
		&self,
		order: &Order,
		_fill_proof: &FillProof,
	) -> Result<Option<Transaction>, SettlementError> {
		let (source_chain, destination_chain) = Self::source_and_destination_chain(order)?;

		let input_oracle = self
			.select_oracle(&self.get_input_oracles(source_chain), None)
			.ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"No input oracle configured for chain {source_chain}"
				))
			})?;
		let output_oracle = self
			.select_oracle(&self.get_output_oracles(destination_chain), None)
			.ok_or_else(|| {
				SettlementError::ValidationFailed(format!(
					"No output oracle configured for chain {destination_chain}"
				))
			})?;

		let state = self.message_tracker.load(&order.id).await?.ok_or_else(|| {
			SettlementError::ValidationFailed("No broadcaster state found".into())
		})?;
		let submission = state
			.submission
			.ok_or_else(|| SettlementError::ValidationFailed("No submission state found".into()))?;

		// If already proven, no pre-claim tx needed.
		let provider = self.providers.get(&source_chain).ok_or_else(|| {
			SettlementError::ValidationFailed(format!("No provider for chain {source_chain}"))
		})?;
		if check_is_proven(
			provider,
			&input_oracle,
			destination_chain,
			address_to_bytes32(&output_oracle),
			address_to_bytes32(&submission.application),
			submission.payload_hash,
		)
		.await
		.unwrap_or(false)
		{
			return Ok(None);
		}

		let proof = state
			.proof
			.ok_or_else(|| SettlementError::ValidationFailed("No generated proof found".into()))?;

		let read_args = RemoteReadArgs {
			route: proof
				.route
				.iter()
				.map(|address| alloy_primitives::Address::from_slice(&address.0))
				.collect(),
			bhpInputs: proof.bhp_inputs.into_iter().map(Into::into).collect(),
			storageProof: proof.storage_proof.into(),
		};

		let call_data = IBroadcasterOracle::verifyMessageCall {
			broadcasterReadArgs: read_args,
			remoteChainId: U256::from(destination_chain),
			remoteOracle: alloy_primitives::Address::from_slice(&output_oracle.0),
			messageData: submission.message_data.into(),
		};

		Ok(Some(Transaction {
			to: Some(input_oracle),
			data: call_data.abi_encode(),
			value: U256::ZERO,
			chain_id: source_chain,
			nonce: None,
			gas_limit: Some(5000000),
			gas_price: None,
			max_fee_per_gas: None,
			max_priority_fee_per_gas: None,
		}))
	}

	async fn handle_transaction_confirmed(
		&self,
		order: &Order,
		tx_type: TransactionType,
		receipt: &TransactionReceipt,
	) -> Result<(), SettlementError> {
		match tx_type {
			TransactionType::PostFill => {
				let (source_chain, destination_chain) = Self::source_and_destination_chain(order)?;
				let output_oracle = self
					.select_oracle(&self.get_output_oracles(destination_chain), None)
					.ok_or_else(|| {
						SettlementError::ValidationFailed(format!(
							"No output oracle configured for chain {destination_chain}"
						))
					})?;

				let output_settler = order
					.output_chains
					.first()
					.ok_or_else(|| SettlementError::ValidationFailed("No output chain".into()))?
					.settler_address
					.clone();

				let fill_logs = self
					.fetch_fill_receipt_logs(order, destination_chain)
					.await?;
				let fill_payload = self.parse_fill_payload_from_logs(order, &fill_logs)?;
				let payload_hash = keccak256(&fill_payload);
				let payloads = vec![fill_payload];

				let message_data =
					encode_message_data(address_to_bytes32(&output_settler), &payloads)?;
				let computed_message = compute_broadcaster_message(&output_settler, &payloads);
				let actual_message = self
					.extract_message_from_broadcast_logs(&receipt.logs, &output_oracle)
					.ok_or_else(|| {
						SettlementError::ValidationFailed(
							"MessageBroadcast event not found in PostFill receipt".to_string(),
						)
					})?;
				if actual_message != computed_message {
					return Err(SettlementError::SlotDerivationMismatch);
				}

				self.message_tracker
					.track_submission(
						&order.id,
						BroadcasterSubmission {
							source_chain,
							destination_chain,
							submission_tx_hash: receipt.hash.clone(),
							submission_timestamp: now_seconds(),
							submission_block_number: Some(receipt.block_number),
							payload_hash,
							message: computed_message,
							message_data,
							application: output_settler,
							remote_oracle: output_oracle,
						},
					)
					.await?;
			},
			TransactionType::PreClaim => {
				self.message_tracker.mark_verified(&order.id).await?;
			},
			_ => {},
		}

		Ok(())
	}
}

/// Reject negative TOML integers and cast to u64.
///
/// TOML integers are `i64`; casting a negative value with `as u64` silently
/// wraps to a huge number.  This helper makes the rejection explicit.
fn parse_nonneg_u64(raw: i64, field: &str, index: usize) -> Result<u64, SettlementError> {
	if raw < 0 {
		Err(SettlementError::ValidationFailed(format!(
			"pusher_directions[{index}].{field} must be non-negative, got {raw}"
		)))
	} else {
		Ok(raw as u64)
	}
}

/// Parse pusher directions from TOML configuration.
///
/// Reads the optional `pusher_directions` array from config. For each entry,
/// required fields are `pusher_address`, `buffer_address`, `push_cooldown_seconds`,
/// and either `l2_params` (typed, preferred) or `l2_transaction_data` (legacy hex).
///
/// `l1_chain_id` / `l2_chain_id` are optional **only** when the oracle config
/// contains exactly one route with exactly one destination — an unambiguous
/// mapping.  They are required when multiple routes or destinations are present.
///
/// All integer fields must be non-negative.  Labels must be unique across
/// all entries in the array.
fn parse_pusher_directions(
	config: &toml::Value,
	oracle_config: &OracleConfig,
) -> Result<Vec<PusherDirection>, SettlementError> {
	let Some(directions_value) = config.get("pusher_directions") else {
		return Ok(vec![]);
	};

	let directions_array = directions_value.as_array().ok_or_else(|| {
		SettlementError::ValidationFailed("pusher_directions must be an array".into())
	})?;

	// Infer default chain IDs only when there is exactly one unambiguous route.
	// Multiple source chains or multiple destinations make the mapping ambiguous,
	// so we require explicit values in those cases.
	let (default_l1_chain_id, default_l2_chain_id) = if oracle_config.routes.len() == 1 {
		let (&l1, dests) = oracle_config.routes.iter().next().unwrap();
		let l2 = if dests.len() == 1 {
			Some(dests[0])
		} else {
			None
		};
		(Some(l1), l2)
	} else {
		(None, None)
	};

	let directions: Vec<PusherDirection> = directions_array
		.iter()
		.enumerate()
		.map(|(i, entry)| {
			// ── chain IDs ────────────────────────────────────────────────────
			let l1_chain_id = if let Some(v) = entry.get("l1_chain_id") {
				let raw = v.as_integer().ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].l1_chain_id must be integer"
					))
				})?;
				parse_nonneg_u64(raw, "l1_chain_id", i)?
			} else {
				default_l1_chain_id.ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].l1_chain_id is required \
                         (multiple routes configured — no unambiguous default)"
					))
				})?
			};

			let l2_chain_id = if let Some(v) = entry.get("l2_chain_id") {
				let raw = v.as_integer().ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].l2_chain_id must be integer"
					))
				})?;
				parse_nonneg_u64(raw, "l2_chain_id", i)?
			} else {
				default_l2_chain_id.ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].l2_chain_id is required \
                         (multiple destinations configured — no unambiguous default)"
					))
				})?
			};

			// ── addresses ────────────────────────────────────────────────────
			let pusher_addr_str = entry
				.get("pusher_address")
				.and_then(|v| v.as_str())
				.ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].pusher_address is required"
					))
				})?;
			let pusher_address =
				solver_types::utils::parse_address(pusher_addr_str).map_err(|e| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].pusher_address invalid: {e}"
					))
				})?;

			let buffer_addr_str = entry
				.get("buffer_address")
				.and_then(|v| v.as_str())
				.ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].buffer_address is required"
					))
				})?;
			let buffer_address =
				solver_types::utils::parse_address(buffer_addr_str).map_err(|e| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].buffer_address invalid: {e}"
					))
				})?;

			// ── required integer fields ───────────────────────────────────────
			let cooldown_raw = entry
				.get("push_cooldown_seconds")
				.and_then(|v| v.as_integer())
				.ok_or_else(|| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].push_cooldown_seconds is required"
					))
				})?;
			let push_cooldown_seconds = parse_nonneg_u64(cooldown_raw, "push_cooldown_seconds", i)?;

			// ── l2_params (typed, preferred) / l2_transaction_data (legacy) ──
			let l2_params = if let Some(l2_params_val) = entry.get("l2_params") {
				// New typed path.
				let params: PusherL2Params = l2_params_val.clone().try_into().map_err(|e| {
					SettlementError::ValidationFailed(format!(
						"pusher_directions[{i}].l2_params invalid: {e}"
					))
				})?;
				validate_l2_params_chain_match(&params, l2_chain_id, i)?;
				params
			} else if let Some(hex_str) = entry.get("l2_transaction_data").and_then(|v| v.as_str())
			{
				// Legacy hex fallback — warn and infer typed variant from chain ID.
				tracing::warn!(
					index = i,
					"pusher_directions[{i}].l2_transaction_data is deprecated; \
					 use l2_params instead"
				);
				infer_l2_params_from_hex(hex_str, l2_chain_id, i)?
			} else {
				return Err(SettlementError::ValidationFailed(format!(
					"pusher_directions[{i}]: either l2_params or l2_transaction_data \
					 is required"
				)));
			};

			// ── optional integer fields ───────────────────────────────────────
			let batch_size = match entry.get("batch_size").and_then(|v| v.as_integer()) {
				Some(raw) => parse_nonneg_u64(raw, "batch_size", i)?,
				None => 256,
			};

			// ── label ─────────────────────────────────────────────────────────
			let default_label = format!("{l1_chain_id}-to-{l2_chain_id}");
			let label = entry
				.get("label")
				.and_then(|v| v.as_str())
				.unwrap_or(&default_label)
				.to_string();

			Ok(PusherDirection {
				label,
				l1_chain_id,
				pusher_address,
				l2_chain_id,
				buffer_address,
				batch_size,
				push_cooldown_seconds,
				l2_params,
			})
		})
		.collect::<Result<_, _>>()?;

	// Duplicate labels cause incorrect cooldown throttling in the pusher task.
	let mut seen_labels = std::collections::HashSet::new();
	for d in &directions {
		if !seen_labels.insert(d.label.as_str()) {
			return Err(SettlementError::ValidationFailed(format!(
				"pusher_directions: duplicate label {:?} — all labels must be unique",
				d.label
			)));
		}
	}

	Ok(directions)
}

/// Validate that the `PusherL2Params` variant is appropriate for `l2_chain_id`.
///
/// `Raw` is allowed on any chain (explicit override).  All typed variants are
/// restricted to their known chain IDs to catch configuration mistakes early.
fn validate_l2_params_chain_match(
	l2_params: &PusherL2Params,
	l2_chain_id: u64,
	i: usize,
) -> Result<(), SettlementError> {
	let valid = match l2_params {
		PusherL2Params::Arbitrum { .. } => matches!(l2_chain_id, 42161 | 421614),
		PusherL2Params::Linea { .. } => matches!(l2_chain_id, 59144 | 59141),
		PusherL2Params::OpStack { .. } => matches!(l2_chain_id, 10 | 8453 | 11155420 | 84532),
		PusherL2Params::Raw { .. } => true,
	};
	if !valid {
		let type_name = match l2_params {
			PusherL2Params::Arbitrum { .. } => "arbitrum",
			PusherL2Params::Linea { .. } => "linea",
			PusherL2Params::OpStack { .. } => "op_stack",
			PusherL2Params::Raw { .. } => "raw",
		};
		return Err(SettlementError::ValidationFailed(format!(
			"pusher_directions[{i}].l2_params type \"{type_name}\" is not valid \
			 for l2_chain_id {l2_chain_id}"
		)));
	}
	Ok(())
}

/// Convert a legacy hex `l2_transaction_data` string to a typed `PusherL2Params`
/// by inferring the variant from `l2_chain_id`.
///
/// Overflow guard: each ABI word is 32 bytes; we read only the low 8 bytes as
/// `u64`.  Values that exceed 64 bits are silently truncated.  In practice gas
/// parameters and fees never approach 2^64 wei (~18.4 ETH per gas), so this is safe.
fn infer_l2_params_from_hex(
	hex_str: &str,
	l2_chain_id: u64,
	i: usize,
) -> Result<PusherL2Params, SettlementError> {
	let data = hex::decode(hex_str.trim_start_matches("0x")).map_err(|e| {
		SettlementError::ValidationFailed(format!(
			"pusher_directions[{i}].l2_transaction_data invalid hex: {e}"
		))
	})?;

	/// Read a u64 from the low 8 bytes of a 32-byte ABI word at `offset`.
	/// Returns 0 if `data` is too short.
	/// Overflow guard: the high 24 bytes of the word are discarded.
	fn read_u64(data: &[u8], offset: usize) -> u64 {
		let end = offset + 32;
		if data.len() < end {
			return 0;
		}
		// Low 8 bytes of the 32-byte word (overflow guard: high 24 bytes discarded).
		let mut buf = [0u8; 8];
		buf.copy_from_slice(&data[offset + 24..end]);
		u64::from_be_bytes(buf)
	}

	match l2_chain_id {
		// Arbitrum mainnet / Sepolia: 5-word ABI encoding.
		// word 0: inbox address (bytes 12–31), words 1–3: gas params, word 4: isERC20
		42161 | 421614 => {
			if data.len() < 160 {
				return Err(SettlementError::ValidationFailed(format!(
					"pusher_directions[{i}]: ARB l2_transaction_data must be \
					 160 bytes, got {}",
					data.len()
				)));
			}
			let inbox = alloy_primitives::Address::from_slice(&data[12..32]);
			let gas_price_bid = read_u64(&data, 32);
			let gas_limit = read_u64(&data, 64);
			let submission_cost = read_u64(&data, 96);
			let is_erc20_inbox = data[159] != 0;
			Ok(PusherL2Params::Arbitrum {
				inbox,
				gas_price_bid,
				gas_limit,
				submission_cost,
				is_erc20_inbox,
			})
		},
		// Linea mainnet / testnet: first 32 bytes = fee.
		59144 | 59141 => {
			let fee = read_u64(&data, 0);
			Ok(PusherL2Params::Linea { fee })
		},
		// OP Stack: first 32 bytes encodes a uint32 gasLimit.
		10 | 8453 | 11155420 | 84532 => {
			let gas_limit = if data.len() >= 32 {
				// ABI uint32 is right-aligned in 32 bytes; read low 4 bytes.
				let mut buf = [0u8; 4];
				buf.copy_from_slice(&data[28..32]);
				u32::from_be_bytes(buf)
			} else {
				0
			};
			Ok(PusherL2Params::OpStack { gas_limit })
		},
		// Unknown chain: pass data through as Raw with no msg.value.
		_ => Ok(PusherL2Params::Raw {
			data: format!("0x{}", hex::encode(&data)),
			value_wei: None,
		}),
	}
}

/// Factory function to create a broadcaster settlement provider from configuration.
pub fn create_settlement(
	config: &toml::Value,
	networks: &NetworksConfig,
	storage: Arc<StorageService>,
) -> Result<Box<dyn SettlementInterface>, SettlementError> {
	BroadcasterSettlementSchema::validate_config(config)
		.map_err(|e| SettlementError::ValidationFailed(format!("Invalid configuration: {e}")))?;

	let oracle_config = parse_oracle_config(config)?;
	let broadcaster_addresses =
		parse_address_table(config.get("broadcaster_addresses").ok_or_else(|| {
			SettlementError::ValidationFailed("Missing broadcaster_addresses".to_string())
		})?)?;
	let receiver_addresses =
		parse_address_table(config.get("receiver_addresses").ok_or_else(|| {
			SettlementError::ValidationFailed("Missing receiver_addresses".to_string())
		})?)?;
	let broadcaster_ids = parse_b256_table(config.get("broadcaster_ids").ok_or_else(|| {
		SettlementError::ValidationFailed("Missing broadcaster_ids".to_string())
	})?)?;

	let proof_service_url = config
		.get("proof_service_url")
		.and_then(|value| value.as_str())
		.ok_or_else(|| SettlementError::ValidationFailed("Missing proof_service_url".into()))?
		.to_string();

	let proof_wait_time_seconds = config
		.get("proof_wait_time_seconds")
		.and_then(|value| value.as_integer())
		.unwrap_or(30) as u64;
	let storage_proof_timeout_seconds = config
		.get("storage_proof_timeout_seconds")
		.and_then(|value| value.as_integer())
		.unwrap_or(30) as u64;
	let default_finality_blocks = config
		.get("default_finality_blocks")
		.and_then(|value| value.as_integer())
		.unwrap_or(20) as u64;
	let empty_finality_table = toml::Value::Table(toml::map::Map::new());
	let finality_table = config
		.get("finality_blocks")
		.unwrap_or(&empty_finality_table);
	let finality_blocks = parse_u64_table(finality_table)?;

	let pusher_directions = parse_pusher_directions(config, &oracle_config)?;

	let settlement = BroadcasterSettlement::new(
		networks,
		oracle_config,
		broadcaster_addresses,
		receiver_addresses,
		broadcaster_ids,
		proof_service_url,
		proof_wait_time_seconds,
		storage_proof_timeout_seconds,
		default_finality_blocks,
		finality_blocks,
		storage,
		pusher_directions,
	)?;

	Ok(Box::new(settlement))
}

/// Registry for broadcaster settlement implementation.
pub struct Registry;

impl solver_types::ImplementationRegistry for Registry {
	const NAME: &'static str = "broadcaster";
	type Factory = crate::SettlementFactory;

	fn factory() -> Self::Factory {
		create_settlement
	}
}

impl crate::SettlementRegistry for Registry {}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::OracleSelectionStrategy;

	// ── helpers ─────────────────────────────────────────────────────────────

	fn make_oracle_config(routes: HashMap<u64, Vec<u64>>) -> OracleConfig {
		let mut input_oracles = HashMap::new();
		let mut output_oracles = HashMap::new();
		for (&src, dests) in &routes {
			input_oracles.insert(src, vec![solver_types::Address(vec![0u8; 20])]);
			for &dst in dests {
				output_oracles.insert(dst, vec![solver_types::Address(vec![0u8; 20])]);
			}
		}
		OracleConfig {
			input_oracles,
			output_oracles,
			routes,
			selection_strategy: OracleSelectionStrategy::First,
		}
	}

	fn oracle_config_eth_to_op() -> OracleConfig {
		let mut routes = HashMap::new();
		routes.insert(11155111u64, vec![84532u64]);
		make_oracle_config(routes)
	}

	fn empty_oracle_config() -> OracleConfig {
		make_oracle_config(HashMap::new())
	}

	/// Build an inline TOML table for a `PusherL2Params::OpStack` variant.
	fn op_stack_l2_params() -> toml::Value {
		let mut l2p = toml::map::Map::new();
		l2p.insert("type".into(), toml::Value::String("op_stack".into()));
		l2p.insert("gas_limit".into(), toml::Value::Integer(200000));
		toml::Value::Table(l2p)
	}

	/// Build an inline TOML table for a `PusherL2Params::Arbitrum` variant.
	fn arb_l2_params() -> toml::Value {
		let mut l2p = toml::map::Map::new();
		l2p.insert("type".into(), toml::Value::String("arbitrum".into()));
		l2p.insert(
			"inbox".into(),
			toml::Value::String("0xaAe29B0366299461418F5324a79Afc425BE5ae21".into()),
		);
		l2p.insert("gas_price_bid".into(), toml::Value::Integer(100_000_000));
		l2p.insert("gas_limit".into(), toml::Value::Integer(16_000_000));
		l2p.insert(
			"submission_cost".into(),
			toml::Value::Integer(1_000_000_000_000_000i64),
		);
		l2p.insert("is_erc20_inbox".into(), toml::Value::Boolean(false));
		toml::Value::Table(l2p)
	}

	/// Build a minimal valid TOML entry for one pusher direction (no chain IDs).
	/// Uses OpStack l2_params (compatible with the default eth-to-op oracle route).
	fn valid_entry_no_chains() -> toml::Value {
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		t.insert("l2_params".into(), op_stack_l2_params());
		toml::Value::Table(t)
	}

	fn config_with_directions(entries: Vec<toml::Value>) -> toml::Value {
		let mut root = toml::map::Map::new();
		root.insert("pusher_directions".into(), toml::Value::Array(entries));
		toml::Value::Table(root)
	}

	// ── absence / empty ──────────────────────────────────────────────────────

	#[test]
	fn test_no_pusher_directions_key_returns_empty() {
		let config = toml::Value::Table(toml::map::Map::new());
		let result = parse_pusher_directions(&config, &empty_oracle_config()).unwrap();
		assert!(result.is_empty());
	}

	#[test]
	fn test_empty_pusher_directions_array_returns_empty() {
		let config = config_with_directions(vec![]);
		let result = parse_pusher_directions(&config, &empty_oracle_config()).unwrap();
		assert!(result.is_empty());
	}

	// ── defaults inferred from routes ────────────────────────────────────────

	#[test]
	fn test_defaults_inferred_from_routes() {
		let config = config_with_directions(vec![valid_entry_no_chains()]);
		let result = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap();
		assert_eq!(result.len(), 1);
		let d = &result[0];
		assert_eq!(d.l1_chain_id, 11155111);
		assert_eq!(d.l2_chain_id, 84532);
		// Default batch_size = 256
		assert_eq!(d.batch_size, 256);
		// Default label = "<l1>-to-<l2>"
		assert_eq!(d.label, "11155111-to-84532");
		assert_eq!(d.push_cooldown_seconds, 3600);
		// l2_params should be OpStack (inferred via legacy path for OP chain 84532)
		assert!(
			matches!(d.l2_params, PusherL2Params::OpStack { .. }),
			"expected OpStack variant, got {:?}",
			d.l2_params
		);
	}

	// ── all fields explicit ──────────────────────────────────────────────────

	#[test]
	fn test_all_fields_explicit() {
		let mut entry = toml::map::Map::new();
		entry.insert("l1_chain_id".into(), toml::Value::Integer(1));
		entry.insert("l2_chain_id".into(), toml::Value::Integer(10)); // Optimism mainnet
		entry.insert(
			"pusher_address".into(),
			toml::Value::String("0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA".into()),
		);
		entry.insert(
			"buffer_address".into(),
			toml::Value::String("0xBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB".into()),
		);
		entry.insert("push_cooldown_seconds".into(), toml::Value::Integer(7200));
		entry.insert("l2_params".into(), op_stack_l2_params());
		entry.insert("batch_size".into(), toml::Value::Integer(512));
		entry.insert("label".into(), toml::Value::String("mainnet-to-op".into()));

		let config = config_with_directions(vec![toml::Value::Table(entry)]);
		let result = parse_pusher_directions(&config, &empty_oracle_config()).unwrap();
		assert_eq!(result.len(), 1);
		let d = &result[0];
		assert_eq!(d.l1_chain_id, 1);
		assert_eq!(d.l2_chain_id, 10);
		assert_eq!(d.batch_size, 512);
		assert_eq!(d.label, "mainnet-to-op");
		assert_eq!(d.push_cooldown_seconds, 7200);
		assert_eq!(d.l2_params, PusherL2Params::OpStack { gas_limit: 200000 });
	}

	// ── arb l2 chain id with typed arbitrum params ───────────────────────────

	#[test]
	fn test_arb_l2_chain_id_parses_successfully() {
		let mut entry = toml::map::Map::new();
		entry.insert("l1_chain_id".into(), toml::Value::Integer(11155111));
		entry.insert("l2_chain_id".into(), toml::Value::Integer(421614)); // ARB Sepolia
		entry.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		entry.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		entry.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		entry.insert("l2_params".into(), arb_l2_params());

		let config = config_with_directions(vec![toml::Value::Table(entry)]);
		let result = parse_pusher_directions(&config, &empty_oracle_config()).unwrap();
		assert_eq!(result.len(), 1);
		assert_eq!(result[0].l2_chain_id, 421614);
		assert!(matches!(
			result[0].l2_params,
			PusherL2Params::Arbitrum { .. }
		));
	}

	// ── multiple directions ──────────────────────────────────────────────────

	#[test]
	fn test_multiple_directions() {
		let mut routes = HashMap::new();
		routes.insert(1u64, vec![10u64, 8453u64]);
		let oracle_config = make_oracle_config(routes);

		// Two destinations → l2_chain_id is ambiguous; both entries must be explicit.
		// l1_chain_id may still be inferred (1 unambiguous source key).
		let mut entry_a = valid_entry_no_chains();
		let mut entry_b = valid_entry_no_chains();
		if let toml::Value::Table(ref mut t) = entry_a {
			t.insert("l2_chain_id".into(), toml::Value::Integer(10));
			t.insert("label".into(), toml::Value::String("eth-to-op".into()));
		}
		if let toml::Value::Table(ref mut t) = entry_b {
			t.insert("l2_chain_id".into(), toml::Value::Integer(8453));
			t.insert("label".into(), toml::Value::String("eth-to-base".into()));
		}
		let config = config_with_directions(vec![entry_a, entry_b]);
		let result = parse_pusher_directions(&config, &oracle_config).unwrap();
		assert_eq!(result.len(), 2);
		assert_eq!(result[0].l1_chain_id, 1); // inferred from single route key
		assert_eq!(result[0].l2_chain_id, 10);
		assert_eq!(result[0].label, "eth-to-op");
		assert_eq!(result[1].l2_chain_id, 8453);
		assert_eq!(result[1].label, "eth-to-base");
	}

	#[test]
	fn test_l2_chain_id_required_when_multiple_destinations() {
		let mut routes = HashMap::new();
		routes.insert(1u64, vec![10u64, 8453u64]); // 2 dests — ambiguous
		let oracle_config = make_oracle_config(routes);

		// Entry has no l2_chain_id — should fail because default is ambiguous.
		let config = config_with_directions(vec![valid_entry_no_chains()]);
		let err = parse_pusher_directions(&config, &oracle_config).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("l2_chain_id"), "unexpected msg: {msg}");
		assert!(
			msg.contains("multiple destinations"),
			"unexpected msg: {msg}"
		);
	}

	// ── required-field missing errors ────────────────────────────────────────

	#[test]
	fn test_missing_pusher_address() {
		let mut t = toml::map::Map::new();
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		t.insert("l2_params".into(), op_stack_l2_params());
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("pusher_address"), "unexpected msg: {msg}");
	}

	#[test]
	fn test_missing_buffer_address() {
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		t.insert("l2_params".into(), op_stack_l2_params());
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("buffer_address"), "unexpected msg: {msg}");
	}

	#[test]
	fn test_missing_push_cooldown_seconds() {
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("l2_params".into(), op_stack_l2_params());
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(
			msg.contains("push_cooldown_seconds"),
			"unexpected msg: {msg}"
		);
	}

	#[test]
	fn test_missing_l2_params_and_l2_transaction_data() {
		// Neither l2_params nor l2_transaction_data → should fail.
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(
			msg.contains("l2_params") || msg.contains("l2_transaction_data"),
			"unexpected msg: {msg}"
		);
	}

	// ── invalid-value errors ─────────────────────────────────────────────────

	#[test]
	fn test_invalid_l2_params() {
		// l2_params present but with an unknown "type" value → parse error.
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		let mut l2p = toml::map::Map::new();
		l2p.insert(
			"type".into(),
			toml::Value::String("unknown_chain_type".into()),
		);
		t.insert("l2_params".into(), toml::Value::Table(l2p));
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("l2_params"), "unexpected msg: {msg}");
	}

	#[test]
	fn test_invalid_hex_l2_transaction_data_legacy() {
		// Legacy path: l2_transaction_data with invalid hex → should fail.
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		t.insert(
			"l2_transaction_data".into(),
			toml::Value::String("0xnothex!".into()),
		);
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("l2_transaction_data"), "unexpected msg: {msg}");
		assert!(
			msg.contains("invalid hex"),
			"expected 'invalid hex' in: {msg}"
		);
	}

	#[test]
	fn test_invalid_pusher_address_format() {
		let mut t = toml::map::Map::new();
		t.insert(
			"pusher_address".into(),
			toml::Value::String("not-an-address".into()),
		);
		t.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		t.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		t.insert("l2_params".into(), op_stack_l2_params());
		let config = config_with_directions(vec![toml::Value::Table(t)]);

		let err = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("pusher_address"), "unexpected msg: {msg}");
		assert!(msg.contains("invalid"), "expected 'invalid' in: {msg}");
	}

	// ── chain/variant validation ──────────────────────────────────────────────

	#[test]
	fn test_l2_params_chain_mismatch_op_stack_on_arb() {
		// OpStack variant on ARB chain ID should be rejected.
		let mut entry = toml::map::Map::new();
		entry.insert("l1_chain_id".into(), toml::Value::Integer(11155111));
		entry.insert("l2_chain_id".into(), toml::Value::Integer(421614)); // ARB Sepolia
		entry.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		entry.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		entry.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		entry.insert("l2_params".into(), op_stack_l2_params()); // OpStack on ARB → wrong
		let config = config_with_directions(vec![toml::Value::Table(entry)]);

		let err = parse_pusher_directions(&config, &empty_oracle_config()).unwrap_err();
		let msg = err.to_string();
		assert!(
			msg.contains("op_stack") && msg.contains("421614"),
			"unexpected msg: {msg}"
		);
	}

	#[test]
	fn test_l2_params_raw_allowed_on_any_chain() {
		// Raw variant should be accepted on any chain ID.
		let mut entry = toml::map::Map::new();
		entry.insert("l1_chain_id".into(), toml::Value::Integer(1));
		entry.insert("l2_chain_id".into(), toml::Value::Integer(42161)); // ARB mainnet
		entry.insert(
			"pusher_address".into(),
			toml::Value::String("0x1111111111111111111111111111111111111111".into()),
		);
		entry.insert(
			"buffer_address".into(),
			toml::Value::String("0x2222222222222222222222222222222222222222".into()),
		);
		entry.insert("push_cooldown_seconds".into(), toml::Value::Integer(3600));
		let mut l2p = toml::map::Map::new();
		l2p.insert("type".into(), toml::Value::String("raw".into()));
		l2p.insert("data".into(), toml::Value::String("0xdeadbeef".into()));
		entry.insert("l2_params".into(), toml::Value::Table(l2p));
		let config = config_with_directions(vec![toml::Value::Table(entry)]);

		let result = parse_pusher_directions(&config, &empty_oracle_config()).unwrap();
		assert_eq!(result.len(), 1);
		assert!(matches!(result[0].l2_params, PusherL2Params::Raw { .. }));
	}

	// ── legacy l2_transaction_data fallback ───────────────────────────────────

	#[test]
	fn test_l2_transaction_data_legacy_fallback_op_stack() {
		// Old hex string on OP chain → inferred as OpStack variant.
		// The abi.encode(uint32(200000)) = 28 zero bytes + 4 bytes of 200000.
		let gas_limit: u32 = 200000; // 0x30D40
		let mut abi_word = [0u8; 32];
		abi_word[28..32].copy_from_slice(&gas_limit.to_be_bytes());
		let hex_data = format!("0x{}", hex::encode(abi_word));

		let mut entry = valid_entry_no_chains();
		if let toml::Value::Table(ref mut t) = entry {
			// Override l2_params with legacy field to test the fallback.
			t.remove("l2_params");
			t.insert("l2_transaction_data".into(), toml::Value::String(hex_data));
		}
		let config = config_with_directions(vec![entry]);
		let result = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap();
		assert_eq!(result.len(), 1);
		assert_eq!(result[0].l2_params, PusherL2Params::OpStack { gas_limit });
	}

	#[test]
	fn test_l2_transaction_data_legacy_no_0x_prefix() {
		// Legacy hex without 0x prefix should still be accepted.
		let mut entry = valid_entry_no_chains();
		if let toml::Value::Table(ref mut t) = entry {
			t.remove("l2_params");
			t.insert(
				"l2_transaction_data".into(),
				toml::Value::String("deadbeef".into()),
			);
		}
		// deadbeef → 4 bytes, chain 84532 → OpStack, gas_limit from low 4 bytes of 32-byte word.
		// 4 bytes is shorter than 32 → gas_limit defaults to 0.
		let config = config_with_directions(vec![entry]);
		let result = parse_pusher_directions(&config, &oracle_config_eth_to_op()).unwrap();
		assert_eq!(result.len(), 1);
		assert_eq!(
			result[0].l2_params,
			PusherL2Params::OpStack { gas_limit: 0 }
		);
	}

	// ── infer_l2_params_from_hex ─────────────────────────────────────────────

	#[test]
	fn test_infer_l2_params_arb_chain_valid() {
		// Build a 160-byte ARB ABI encoding:
		// word 0 (bytes 0..32): inbox address in bytes 12..32
		// word 1 (bytes 32..64): gas_price_bid
		// word 2 (bytes 64..96): gas_limit
		// word 3 (bytes 96..128): submission_cost
		// word 4 (bytes 128..160): isERC20 flag
		let mut data = vec![0u8; 160];
		// inbox at bytes 12..32
		let inbox_bytes = [0xAAu8; 20];
		data[12..32].copy_from_slice(&inbox_bytes);
		// gas_price_bid = 100_000_000 at word 1 (offset 32), low 8 bytes = offset 56..64
		let gpb: u64 = 100_000_000;
		data[56..64].copy_from_slice(&gpb.to_be_bytes());
		// gas_limit = 16_000_000 at word 2 (offset 64), low 8 bytes = offset 88..96
		let gl: u64 = 16_000_000;
		data[88..96].copy_from_slice(&gl.to_be_bytes());
		// submission_cost = 1_000_000_000_000_000 at word 3 (offset 96), low 8 bytes = offset 120..128
		let sc: u64 = 1_000_000_000_000_000;
		data[120..128].copy_from_slice(&sc.to_be_bytes());
		// is_erc20_inbox = false (byte 159 = 0)

		let hex_str = format!("0x{}", hex::encode(&data));
		let result = infer_l2_params_from_hex(&hex_str, 421614, 0).unwrap();

		let expected_inbox = alloy_primitives::Address::from_slice(&inbox_bytes);
		assert_eq!(
			result,
			PusherL2Params::Arbitrum {
				inbox: expected_inbox,
				gas_price_bid: gpb,
				gas_limit: gl,
				submission_cost: sc,
				is_erc20_inbox: false,
			}
		);
	}

	#[test]
	fn test_infer_l2_params_arb_chain_too_short() {
		// ARB chain but only 32 bytes → must error
		let data = vec![0u8; 32];
		let hex_str = format!("0x{}", hex::encode(&data));
		let err = infer_l2_params_from_hex(&hex_str, 421614, 0).unwrap_err();
		assert!(
			err.to_string().contains("160 bytes"),
			"expected 160-byte error, got: {err}"
		);
	}

	#[test]
	fn test_infer_l2_params_linea_chain() {
		// 32-byte ABI word encoding fee = 1_000_000_000_000_000.
		// read_u64 reads low 8 bytes (offset 24..32).
		let fee: u64 = 1_000_000_000_000_000;
		let mut data = vec![0u8; 32];
		data[24..32].copy_from_slice(&fee.to_be_bytes());
		let hex_str = format!("0x{}", hex::encode(&data));
		let result = infer_l2_params_from_hex(&hex_str, 59144, 0).unwrap();
		assert_eq!(result, PusherL2Params::Linea { fee });
	}

	#[test]
	fn test_infer_l2_params_unknown_chain_returns_raw() {
		let data = vec![0xDEu8, 0xAD, 0xBE, 0xEF];
		let hex_str = format!("0x{}", hex::encode(&data));
		let result = infer_l2_params_from_hex(&hex_str, 1, 0).unwrap();
		assert_eq!(
			result,
			PusherL2Params::Raw {
				data: "0xdeadbeef".to_string(),
				value_wei: None,
			}
		);
	}

	// ── validate_l2_params_chain_match ───────────────────────────────────────

	#[test]
	fn test_validate_l2_params_chain_match_linea_valid() {
		let params = PusherL2Params::Linea { fee: 0 };
		assert!(validate_l2_params_chain_match(&params, 59144, 0).is_ok());
		assert!(validate_l2_params_chain_match(&params, 59141, 0).is_ok());
	}

	#[test]
	fn test_validate_l2_params_chain_mismatch_linea_on_op_chain() {
		let params = PusherL2Params::Linea { fee: 0 };
		let err = validate_l2_params_chain_match(&params, 84532, 0).unwrap_err();
		assert!(
			err.to_string().contains("linea"),
			"expected type name in error: {err}"
		);
		assert!(
			err.to_string().contains("84532"),
			"expected chain_id in error: {err}"
		);
	}

	// ── chain-id inference failures ──────────────────────────────────────────

	#[test]
	fn test_l1_chain_id_required_when_routes_empty() {
		let config = config_with_directions(vec![valid_entry_no_chains()]);
		let err = parse_pusher_directions(&config, &empty_oracle_config()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("l1_chain_id"), "unexpected msg: {msg}");
	}

	#[test]
	fn test_l2_chain_id_required_when_routes_empty_but_l1_explicit() {
		let mut entry = valid_entry_no_chains();
		if let toml::Value::Table(ref mut t) = entry {
			t.insert("l1_chain_id".into(), toml::Value::Integer(1));
			// l2_chain_id intentionally omitted
		}
		let config = config_with_directions(vec![entry]);
		let err = parse_pusher_directions(&config, &empty_oracle_config()).unwrap_err();
		let msg = err.to_string();
		assert!(msg.contains("l2_chain_id"), "unexpected msg: {msg}");
	}
}
